PJ-2008-01-21-0: Enhancem.: using INFOTEXT instead of echo                  Review:    LP

diff --git a/source/dist/util/sgeST/sge_st b/source/dist/util/sgeST/sge_st
--- a/source/dist/util/sgeST/sge_st
+++ b/source/dist/util/sgeST/sge_st
@@ -38,33 +38,47 @@
 
 
 #---------------------------------------------------------------------------
-# show the usage of the standalone command
-# if ADMINUSER = default then execute command unchanged
-STusage()
-{
-   echo "sge_st enable|disable|register|unregister|upgrade|check|enabled|supported|help"
-   echo "---------------------------------------------------------------------------------"
-   echo "       enable   ... enable The Service Tags"
-   echo "       disable  ... disable The Service Tags"
-   echo "       register ... register product"
-   echo "       unregister . unregister product"
-   echo "       check    ... check if the product is registered"
-   echo "       enabled  ... check if the Service Tags are enabled"
-   echo "       supported .. check if the Service Tags packages are installed on host"
-   echo "       help     ... this help"
-}
-
-#---------------------------------------------------------------------------
-# This script can be called with the following arguments:
-#
-#       register    Register the Grid Engine service tag
-#       unregister  Unregister the Grid Engine service tag
-#
 # This script requires the that $SGE_ROOT and $SGE_CELL be set
 #
 
+if [ -z "$SGE_ROOT" -o -z "$SGE_CELL" ]; then
+   echo "\$SGE_ROOT and \$SGE_CELL must be set to valid values"
+   exit 1
+fi
+
 if [ -z "$ARCH" ]; then
    ARCH=`$SGE_ROOT/util/arch`
+fi
+
+if [ -z "$V5UTILBIN" ]; then
+   V5UTILBIN=$SGE_ROOT/utilbin/$ARCH              # adminrun, infotext, openssl, uidgid
+fi
+
+if [ ! -d "$V5UTILBIN" ]; then
+   echo
+   echo "Error: The utilbin directory "$V5UTILBIN" does not exist"
+   echo "Please verify your setup and restart this script. Exit."
+   exit 1
+fi
+
+if [ -z "$INFOTEXT" ]; then
+   INFOTXT_DUMMY=$V5UTILBIN/infotext
+   INFOTEXT=$INFOTXT_DUMMY
+   if [ ! -x $INFOTXT_DUMMY ]; then
+      echo "Error: Can't find binary \"$INFOTXT_DUMMY\""
+      echo "Please verify your setup and restart this script. Exit."
+      exit 1
+   fi
+
+   # Test the infotext binary
+   tmp=`$INFOTEXT test 2>&1`
+   if [ $? -ne 0 ]; then
+      echo "Error: Execution of $INFOTEXT failed: $tmp"
+      echo "Please verify your setup and restart this script. Exit."
+      exit 1
+   fi
+
+   SGE_INFOTEXT_MAX_COLUMN=5000; export SGE_INFOTEXT_MAX_COLUMN
 fi
 
 # ST are supported just on linux and solaris
@@ -73,7 +87,7 @@ case $ARCH in
    ;;
   *) 
    if [ -z "$2" ]; then
-      echo "The service tags are not supported"
+      $INFOTEXT "The service tags are not supported"
    fi  
    exit 0
    ;;  
@@ -83,6 +97,23 @@ esac
 #customized cut
 CUT=cut
 
+#---------------------------------------------------------------------------
+# show the usage of the standalone command
+# if ADMINUSER = default then execute command unchanged
+STusage()
+{
+   $INFOTEXT "sge_st enable|disable|register|unregister|upgrade|check|enabled|supported|help"
+   $INFOTEXT " -------------------------------------------------------------------------------"
+   $INFOTEXT "       enable   ... enable The Service Tags"
+   $INFOTEXT "       disable  ... disable The Service Tags"
+   $INFOTEXT "       register ... register product"
+   $INFOTEXT "       unregister . unregister product"
+   $INFOTEXT "       check    ... check if the product is registered"
+   $INFOTEXT "       enabled  ... check if the Service Tags are enabled"
+   $INFOTEXT "       supported .. check if the Service Tags packages are installed on host"
+   $INFOTEXT "       help     ... this help"
+}
+
 #-------------------------------------------------------------------------
 #arch_variables Setting up common variables and paths
 #
@@ -91,7 +122,7 @@ STArchVariables()
    if [ -f "$SGE_ROOT/util/arch_variables" ]; then
      . $SGE_ROOT/util/arch_variables
    else
-      echo "Could not source arch_variables"
+      $INFOTEXT "Could not source arch_variables"
       exit 1
    fi
 }
@@ -105,7 +136,7 @@ STBasicSettings()
    if [ -f "$SGE_ROOT/util/sgeST/st_settings.sh" ]; then
       . $SGE_ROOT/util/sgeST/st_settings.sh
    else
-      echo "Could not source basic settings"
+      $INFOTEXT "Could not source basic settings"
       exit 1
    fi
 }
@@ -153,9 +184,9 @@ STEnable()
       echo $PRODUCT_URN >> $st_file
       result=`STShowEnabled`
       if [ $result = "true" ]; then
-         echo "Sun Service Tags are now enabled"
+         $INFOTEXT "Sun Service Tags are now enabled"
       else
-         echo "Sun Service Tags could not be enabled"
+         $INFOTEXT "Sun Service Tags could not be enabled"
          return 1
       fi
    fi   
@@ -172,9 +203,9 @@ STDisable()
       ExecuteAsAdmin $RM $st_file
       result=`STShowEnabled`
       if [ $result = "false" ]; then
-         echo "Sun Service Tags are now disabled"
+         $INFOTEXT "Sun Service Tags are now disabled"
       else 
-         echo "Sun Service Tags could not be disabled"
+         $INFOTEXT "Sun Service Tags could not be disabled"
          return 1
       fi
    fi      
@@ -244,12 +275,12 @@ STClient()
    #get the stclinet with full path
    stclient=`STgetServiceTagClient`
    if [ "$stclient" = "undefined" ]; then
-      echo "The service tags are not supported"    
+      $INFOTEXT "The service tags are not supported"    
       return 1
    fi 
    #the executeble file must exist
    if [ ! -x "$stclient" ]; then
-      echo "The service tags are not installed correctly" 
+      $INFOTEXT "The service tags are not installed correctly" 
       return 1
    fi
 
@@ -292,9 +323,9 @@ STShowRegistered()
       #check again, to be sure wos done
       instance_urn=`STgetInstanceUrn "$stclient" "$product_defined_id"`
       if [ -n "$instance_urn" ]; then
-         echo "registered:$instance_urn"
+         $INFOTEXT "registered:%s" "$instance_urn"
       else
-         echo "unregistered"
+         $INFOTEXT "unregistered"
       fi
    fi   
 }
@@ -408,20 +439,6 @@ STServiceTag()
    if [ "$#" -lt 1 -o  "$#" -gt 2 -o "$command" = "-h" -o "$command" = "help" ]; then
       STusage
       return 0
-   fi
-
-   if [ -z "$SGE_ROOT" -o -z "$SGE_CELL" ]; then
-      echo "\$SGE_ROOT and \$SGE_CELL must be set to valid values"
-      exit 1
-   fi
-
-   V5UTILBIN=$SGE_ROOT/utilbin/$ARCH              # adminrun, infotext, openssl, uidgid
-
-   if [ ! -d "$V5UTILBIN" ]; then
-      echo
-      echo "Error: The utilbin directory "$V5UTILBIN" does not exist"
-      echo "Please verify your setup and restart this script. Exit."
-      exit 1
    fi
 
    #Architecture related variables
