LP-2008-01-24-0: Enhancem.: Subprocesses start in new contracts if SMF is used                  Enhancem.: Various SMF support improvements                  Enhancem.: Startup scripts now support -nosmf option                  Bugfix:    load sensor might block execd port                  Bugster:   6654696                  Review:    RD

diff --git a/source/dist/util/rctemplates/sgebdb_template b/source/dist/util/rctemplates/sgebdb_template
--- a/source/dist/util/rctemplates/sgebdb_template
+++ b/source/dist/util/rctemplates/sgebdb_template
@@ -269,6 +269,10 @@ DetectSMFService()
 {
    name=$1
    service=""
+
+   if [ "$noSMF" = true ]; then
+      return
+   fi
    #Otherwise we try is it's available of the system
    if [ -f /lib/svc/share/smf_include.sh ]; then
       . /lib/svc/share/smf_include.sh
@@ -280,10 +284,22 @@ DetectSMFService()
       return
    fi
 
+   #Check we have cluster_name file
+   if [ ! -r "$SGE_ROOT/$SGE_CELL/common/cluster_name" ]; then
+      echo "Error: could not find $SGE_ROOT/$SGE_CELL/common/cluster_name!"
+      exit $SMF_EXIT_ERR_CONFIG
+   fi
    #Cluster name must be unique
    SGE_CLUSTER_NAME=`cat $SGE_ROOT/$SGE_CELL/common/cluster_name 2>/dev/null`
-
+   
    service="svc:/application/sge/$name:$SGE_CLUSTER_NAME"
+
+   if [ -n "$SMF_FMRI" -a "$service" != "$SMF_FMRI" ]; then
+      #Someone is trying to fool us
+      echo "Error: $service does not match FMRI $SMF_FMRI provided by SMF!"
+      echo "Check that service instance $SGE_CLUSTER_NAME exist on your system"
+      exit $SMF_EXIT_ERR_CONFIG
+   fi
    #Check if service exists
    /usr/bin/svcs $service > /dev/null 2>&1
    if [ $? -ne 0 ]; then
@@ -313,11 +329,15 @@ if [ "$#" -gt 1 -o "$#" -lt 1 -o "$1" = "-h" -o "$1" = "help" ]; then
    usage
 fi
 
+noSMF=false
+
 for i in $*; do
    if [ "$i" = start ]; then
       startup=true
    elif [ "$i" = stop ]; then
       startup=false
+   elif [ "$i" = -nosmf ]; then
+      noSMF=true
    else
       usage
    fi
@@ -331,7 +351,7 @@ fi
 
 if [ "$startup" = true ]; then
    DetectSMFService bdb
-   if [ -z "$BDB_SMF" -a -n "$service" ]; then
+   if [ -z "$SMF_FMRI" -a -n "$service" ]; then
       /usr/sbin/svcadm enable -st $service
       exit $?
    fi
diff --git a/source/dist/util/rctemplates/sgeexecd_template b/source/dist/util/rctemplates/sgeexecd_template
--- a/source/dist/util/rctemplates/sgeexecd_template
+++ b/source/dist/util/rctemplates/sgeexecd_template
@@ -119,6 +119,10 @@ DetectSMFService()
 {
    name=$1
    service=""
+
+   if [ "$noSMF" = true ]; then
+      return
+   fi
    #Otherwise we try is it's available of the system
    if [ -f /lib/svc/share/smf_include.sh ]; then
       . /lib/svc/share/smf_include.sh
@@ -130,10 +134,22 @@ DetectSMFService()
       return
    fi
 
+   #Check we have cluster_name file
+   if [ ! -r "$SGE_ROOT/$SGE_CELL/common/cluster_name" ]; then
+      echo "Error: could not find $SGE_ROOT/$SGE_CELL/common/cluster_name!"
+      exit $SMF_EXIT_ERR_CONFIG
+   fi
    #Cluster name must be unique
    SGE_CLUSTER_NAME=`cat $SGE_ROOT/$SGE_CELL/common/cluster_name 2>/dev/null`
-
+   
    service="svc:/application/sge/$name:$SGE_CLUSTER_NAME"
+
+   if [ -n "$SMF_FMRI" -a "$service" != "$SMF_FMRI" ]; then
+      #Someone is trying to fool us
+      echo "Error: $service does not match FMRI $SMF_FMRI provided by SMF!"
+      echo "Check that service instance $SGE_CLUSTER_NAME exist on your system"
+      exit $SMF_EXIT_ERR_CONFIG
+   fi
    #Check if service exists
    /usr/bin/svcs $service > /dev/null 2>&1
    if [ $? -ne 0 ]; then
@@ -148,7 +164,6 @@ DetectSMFService()
 #
 ShutdownSMF()
 {
-   DetectSMFService execd
    if [ -z "$service" ]; then
       #We don't have any such SMF service we use normal Shutdown
       return
@@ -291,6 +306,7 @@ fi
 startup=true
 execd=true
 softstop=false
+noSMF=false
 
 for i in $*; do
    if [ "$i" = start ]; then
@@ -300,6 +316,8 @@ for i in $*; do
    elif [ "$i" = softstop ]; then
       startup=false
       softstop=true
+   elif [ "$i" = -nosmf ]; then
+      noSMF=true
    else
       usage
    fi
@@ -322,11 +340,11 @@ fi
 HOST=`$utilbin_dir/gethostname -aname`
 UQHOST=`$utilbin_dir/gethostname -name | cut -f1 -d.`
 
+DetectSMFService execd
+
 if [ "$startup" = true ]; then
-      DetectSMFService execd
-      #EXECD_SMF is set to true when script gets called via SMF
       #We want to use smf
-      if [ -z "$EXECD_SMF" -a -n "$service"  ]; then
+      if [ -z "$SMF_FMRI" -a -n "$service"  ]; then
          svcadm enable -st $service
          exit $?
       fi
diff --git a/source/dist/util/rctemplates/sgemaster_template b/source/dist/util/rctemplates/sgemaster_template
--- a/source/dist/util/rctemplates/sgemaster_template
+++ b/source/dist/util/rctemplates/sgemaster_template
@@ -331,6 +331,10 @@ DetectSMFService()
 {
    name=$1
    service=""
+
+   if [ "$noSMF" = true ]; then
+      return
+   fi
    #Otherwise we try is it's available of the system
    if [ -f /lib/svc/share/smf_include.sh ]; then
       . /lib/svc/share/smf_include.sh
@@ -342,10 +346,22 @@ DetectSMFService()
       return
    fi
 
+   #Check we have cluster_name file
+   if [ ! -r "$SGE_ROOT/$SGE_CELL/common/cluster_name" ]; then
+      echo "Error: could not find $SGE_ROOT/$SGE_CELL/common/cluster_name!"
+      exit $SMF_EXIT_ERR_CONFIG
+   fi
    #Cluster name must be unique
    SGE_CLUSTER_NAME=`cat $SGE_ROOT/$SGE_CELL/common/cluster_name 2>/dev/null`
-
+   
    service="svc:/application/sge/$name:$SGE_CLUSTER_NAME"
+
+   if [ -n "$SMF_FMRI" -a "$service" != "$SMF_FMRI" ]; then
+      #Someone is trying to fool us
+      echo "Error: $service does not match FMRI $SMF_FMRI provided by SMF!"
+      echo "Check that service instance $SGE_CLUSTER_NAME exist on your system"
+      exit $SMF_EXIT_ERR_CONFIG
+   fi
    #Check if service exists
    /usr/bin/svcs $service > /dev/null 2>&1
    if [ $? -ne 0 ]; then
@@ -393,6 +409,7 @@ shadowd=true
 qstd=false
 migrate_qmaster=false
 softstop=false
+noSMF=false
 
 for i in $*; do
    if [ "$i" = start ]; then
@@ -412,6 +429,8 @@ for i in $*; do
       migrate_qmaster=true
       qmaster=true
       shadowd=false
+   elif [ "$i" = -nosmf ]; then
+      noSMF=true
    else
       usage
    fi
@@ -510,9 +529,8 @@ if [ "$startup" = true ]; then
 
    if [ $qmaster = true -a $qmaster_host = true ]; then
       DetectSMFService qmaster
-      #QMASTER_SMF is set to true when script gets called via SMF
       #We want to use smf
-      if [ -z "$QMASTER_SMF" -a -n "$service"  ]; then
+      if [ -z "$SMF_FMRI" -a -n "$service"  ]; then
          svcadm enable -st $service
          exit $?
       fi
@@ -553,9 +571,8 @@ if [ "$startup" = true ]; then
 
       if [ $start_shadowd = true ]; then
          DetectSMFService shadowd
-         #SHADOWD_SMF is set to true when script gets called via SMF
          #We want to use smf
-         if [ -z "$SHADOWD_SMF" -a -n "$service"  ]; then
+         if [ -z "$SMF_FMRI" -a -n "$service"  ]; then
             svcadm enable -st $service
             exit $?
          fi
@@ -567,13 +584,13 @@ if [ "$startup" = true ]; then
    fi
 else
    if [ $shadow_host = true ]; then
-      # Send SIGTERM to shadowd
       echo "   Shutting down Grid Engine shadowd"
       DetectSMFService shadowd
-      if [ -n "$service"  ]; then
+      if [ -z "$SMF_FMRI" -a -n "$service"  ]; then
             svcadm disable -st $service
             exit $?
       fi
+      # Send SIGTERM to shadowd
       if [ -f $qmaster_spool_dir/shadowd_$UQHOST.pid ]; then
          Shutdown sge_shadowd $qmaster_spool_dir/shadowd_$UQHOST.pid
       elif [ -f $qmaster_spool_dir/shadowd_$HOST.pid ]; then
@@ -583,13 +600,13 @@ else
 
    if [ $qmaster = true ]; then
       if [ `CheckIfQmasterHost $HOST` = true ]; then
-         # Send SIGTERM to qmaster
          echo "   Shutting down Grid Engine qmaster"
          DetectSMFService qmaster
-         if [ -n "$service"  ]; then
+         if [ -z "$SMF_FMRI" -a -n "$service"  ]; then
             svcadm disable -st $service
             exit $?
          fi
+         # Send SIGTERM to qmaster
          Shutdown sge_qmaster $qmaster_spool_dir/qmaster.pid
          ret=$?
          if [ -f /var/lock/subsys/sgemaster ]; then
