AA-2002-07-23-0: I18N:      sge_ca script infotextized

diff --git a/source/dist/util/sgeCA/sge_ca b/source/dist/util/sgeCA/sge_ca
--- a/source/dist/util/sgeCA/sge_ca
+++ b/source/dist/util/sgeCA/sge_ca
@@ -45,9 +45,6 @@ PATH=/bin:/usr/bin:/usr/ucb
 CLEAR=clear
 #CLEAR=:
 
-# set to false if you don't want this script uses the i18n functions
-#
-SGE_I18N=true
 
 #-------------------------------------------------------------------------
 # USEFUL LOCAL SHELL PROCEDURES
@@ -58,24 +55,15 @@ SGE_I18N=true
 ErrUsage()
 {
    myname=`basename $0`
-   $ECHO "" >&2
-   Translate 3 "Usage:"
-   $ECHO     " $1 {-init|-req|-sign|-copy|-verify|-usercert <file>} [-days <days>]" >&2
-   $ECHO     "    -init           \c" >&2
-   Translate 1 "initialize CA infrastructure"
-   $ECHO     "    -req           \c" >&2
-   Translate 1 "generate a certificate request and private key"
-   $ECHO     "    -sign          \c" >&2
-   Translate 1 "sign a certificate request"
-   $ECHO     "    -copy          \c" >&2
-   Translate 1 "install user certificate and private key"
-   $ECHO     "    -verify        \c" >&2
-   Translate 1 "verify a certificate" 2 1 "\$$SGE_ROOT"
-   $ECHO     "    -days <days>   \c" >&2
-   Translate 1 "days of validity of the certificate"
-   $ECHO     "    -usercert <file>   \c" >&2
-   Translate 1 "generate certificates and keys for the users in <file>"
-   $ECHO "" >&2
+   $INFOTEXT -e \
+   "\nUsage: %s {-init|-req|-sign|-copy|-verify|-usercert <file>} [-days <days>]\n" \
+   "   -init            initialize CA infrastructure\n" \
+   "   -req             generate a certificate request and private key\n" \
+   "   -sign            sign a certificate request\n" \
+   "   -copy            install user certificate and private key\n" \
+   "   -verify          verify a certificate\n" \
+   "   -days <days>     days of validity of the certificate\n" \
+   "   -usercert <file> generate certificates and keys for the users in <file>\n" $myname
 
    exit 1
 }
@@ -86,24 +74,14 @@ ErrUsage()
 InitCA()
 {
    $CLEAR
-   $ECHO
-   Translate 0 "Initializing Certificate Authority (CA) for OpenSSL security framework"
-   $ECHO "----------------------------------------------------------------------"
-   $ECHO
+   $INFOTEXT -u "\nInitializing Certificate Authority (CA) for OpenSSL security framework"
 
    if [ -d $CATOP -o -d $CALOCALTOP ]; then
-      Translate 0 "There are already directories of the CA infrastructure in"
-      $ECHO
-      $ECHO "   $CATOP "
-      Translate 0 "      or    "
-      $ECHO "   $CALOCALTOP "
-      $ECHO
-      Translate 4 "Do you want to recreate your SGE CA infrastructure"
-      YesNo "\n$transout" y
+      $INFOTEXT -e "\nThere are already directories of the CA infrastructure in\n   %s\n   or\n   %s\n" "$CATOP" "$CALOCALTOP"
+      $INFOTEXT -auto $autoinst -ask "y" "n" -def "y" -n \
+         "Do you want to recreate your SGE CA infrastructure (y/n) [y] >> "
       if [ $? != 0 ]; then
-         $ECHO
-         Translate 0 "We will not reinitialize your SGE CA infrastructure"
-         $ECHO
+         $INFOTEXT "We will not reinitialize your SGE CA infrastructure."
          exit 0
       fi
    fi
@@ -111,10 +89,6 @@ InitCA()
    MakeCADirs
 
    MakeCAcert
-
-   Translate 0 "Creating Daemon certificate and key"
-   $ECHO "-----------------------------------"   
-   $ECHO
 
  
    MakeCert daemon $ME "SGE Daemon" none
@@ -154,14 +128,14 @@ InstallKey()
    HOST=`$V5UTILBIN/gethostname -aname`
    result=`CheckIfQmasterHost $HOST`
    if [ "$result" != "true" ]; then 
-      Translate 0 "You can install your private key and certificate only on the master host."
+      $INFOTEXT "You can install your private key and certificate only on the master host."
       return 1
    fi 
 
    if [ -d /var/sgeCA/$CA_PORT/$SGE_CELL/userkeys ]; then
       userkeydir=/var/sgeCA/$CA_PORT/$SGE_CELL/userkeys
    else
-      Translate 0 "Cant find Certificate Authority >%s<." 
+      $INFOTEXT "Cant find local userkey directory."
       return 1
    fi   
 
@@ -211,7 +185,7 @@ InstallKey()
    $V5UTILBIN/adminrun $2 $CHMOD 755 $basedir/certs
    $V5UTILBIN/adminrun $2 $CHMOD 444 $basedir/certs/*
 
-   Translate 0 "Certificate and private key for user $ME have been installed"
+   $INFOTEXT "Certificate and private key for user %s have been installed" $ME
 
    return 0
 }
@@ -223,33 +197,26 @@ InstallKey()
 #
 MakeCAcert()
 {
-   WaitClear clear
+   $INFOTEXT -u "\nCreating CA certificate and private key"
+   $INFOTEXT -e "Please give some basic parameters to create the distinguished name (DN)\n" \
+   "for the certificates.\n\n" \
+   "We will ask for\n" \
+   "   - the two letter country code\n" \
+   "   - the state\n" \
+   "   - the location, e.g city or your buildingcode\n" \
+   "   - the organization (e.g. your company name)\n" \
+   "   - the organizational unit, e.g. your department\n" \
+   "   - the email address of the CA administrator (you!)\n"
 
-   $ECHO
-   Translate 0 "Creating CA certificate and private key"
-   $ECHO "---------------------------------------"
-   $ECHO
-   Translate 0 "Please give some basic parameters to create the distinguished name (DN)"
-   Translate 0 "for the certificates."
-   $ECHO
-   Translate 0 "We will ask for"
-   $ECHO
-   Translate 0 "   - the two letter country code"
-   Translate 0 "   - the state"
-   Translate 0 "   - the location, e.g city or your buildingcode"
-   Translate 0 "   - the organization (e.g. your company name)"
-   Translate 0 "   - the organizational unit, e.g. your department"
-   Translate 0 "   - the email address of the CA administrator (you!)"
-   $ECHO
-   WaitClear clear
-   $ECHO
+   $INFOTEXT -wait -auto $autoinst -n "\nHit <RETURN> to continue >> "
+   # $CLEAR
 
    done=false
    while [ $done = false ]; do
 
       dndone=false
       while [ $dndone = false ]; do
-         Translate 2 "Please enter your two letter country code, e.g. >US< >> "
+         $INFOTEXT -n "Please enter your two letter country code, e.g. >US< >> "
          INP=`Enter ""`
          if [ "$INP != " -a `echo $INP | wc -c` = 3 ]; then
             CA_C=`echo $INP | env LC_ALL=C tr "[a-z]" "[A-Z]"`
@@ -259,7 +226,7 @@ MakeCAcert()
 
       dndone=false
       while [ $dndone = false ]; do
-         Translate 2 "Please enter your state >> "
+         $INFOTEXT -n "Please enter your state >> "
          INP=`Enter ""`
          CA_ST="$INP"
          if [ "$INP" != "" ]; then
@@ -271,7 +238,7 @@ MakeCAcert()
 
       dndone=false
       while [ $dndone = false ]; do
-			Translate 2 "Please enter your location, e.g city or buildingcode >> "
+			$INFOTEXT -n "Please enter your location, e.g city or buildingcode >> "
 			INP=`Enter ""`
 			CA_L="$INP"
          if [ "$INP" != "" ]; then
@@ -282,7 +249,7 @@ MakeCAcert()
 
       dndone=false
       while [ $dndone = false ]; do
-         Translate 2 "Please enter the name of your organization >> "
+         $INFOTEXT -n "Please enter the name of your organization >> "
          INP=`Enter ""`   
          if [ "$INP" != "" ]; then
             CA_O="$INP"
@@ -292,7 +259,7 @@ MakeCAcert()
 
       dndone=false
       while [ $dndone = false ]; do
-         Translate 2 "Please enter your organizational unit, e.g. your department >> "
+         $INFOTEXT -n "Please enter your organizational unit, e.g. your department >> "
          INP=`Enter ""`    
          CA_OU="$INP"
          if [ "$INP" != "" ]; then
@@ -303,7 +270,7 @@ MakeCAcert()
 
       dndone=false
       while [ $dndone = false ]; do
-         Translate 2 "Please enter the email address of the CA administrator >> "
+         $INFOTEXT -n "Please enter the email address of the CA administrator >> "
          INP=`Enter ""`   
          if [ "$INP" != "" ]; then
             CA_EMAIL="$INP"
@@ -313,19 +280,17 @@ MakeCAcert()
 
 
       $CLEAR
-      $ECHO
-      Translate 0 "You selected the following basic data for the distinguished name of"
-      Translate 0 "your certificates:"
-      $ECHO
-      Translate 0 "Country code:         %s=%s" C "$CA_C"
-      Translate 0 "State:                %s=%s" ST "$CA_ST"
-      Translate 0 "Location:             %s=%s" L "$CA_L"
-      Translate 0 "Organization:         %s=%s" O "$CA_O"
-      Translate 0 "Organizational unit:  %s=%s" OU "$CA_OU"
-      Translate 0 "CA email address:     %s=%s" emailAddress "$CA_EMAIL"
-      $ECHO
-      Translate 4 "Do you want to use these data"
-      YesNo "\n$transout" y
+      $INFOTEXT -e "\nYou selected the following basic data for the distinguished name of\n" \
+      "your certificates:\n\n" \
+      "Country code:         %s=%s\n" \
+      "State:                %s=%s\n" \
+      "Location:             %s=%s\n" \
+      "Organization:         %s=%s\n" \
+      "Organizational unit:  %s=%s\n" \
+      "CA email address:     %s=%s\n" \
+      C "$CA_C" ST "$CA_ST" L "$CA_L" O "$CA_O" OU "$CA_OU" emailAddress "$CA_EMAIL"
+      $INFOTEXT -auto $autoinst -ask "y" "n" -def "y" -n \
+         "Do you want to use these data (y/n) [y] >> "
 
       if [ $? = 0 ]; then
          done=true
@@ -352,8 +317,7 @@ MakeCAcert()
             RANDFILE=$CALOCALTOP/private/rand.seed; export RANDFILE
          fi
 
-         Translate 0 "Creating CA certificate and private key"
-         $ECHO
+         $INFOTEXT "Creating CA certificate and private key"
          ExecuteAsAdmin $REQ -config $TMPFILE1 -new -x509 \
               -keyout ${CALOCALTOP}/private/$CAKEY -out ${CATOP}/$CACERT $DAYS
          status=$?
@@ -364,7 +328,7 @@ MakeCAcert()
          rm -f $TMPFILE $TMPFILE1
 
          if [ $status != 0 ]; then
-            Translate 0 "Failed to create CA certificate and private key. Exit"
+            $INFOTEXT "Failed to create CA certificate and private key. Exit"
             exit 1
          fi
 
@@ -372,7 +336,9 @@ MakeCAcert()
          $CLEAR
       fi
    done
-   WaitClear clear
+
+   $INFOTEXT -wait -auto $autoinst -n "\nHit <RETURN> to continue >> "
+   $CLEAR
 }
 
 #--------------------------------------------------------------------------
@@ -389,8 +355,7 @@ MakeRandFile()
    elif [ -f /bin/vi ]; then
       rfile=/bin/vi
    fi
-   Translate 0 "Creating RANDFILE from >%s< in >%s<" $rfile $1
-   $ECHO
+   $INFOTEXT "Creating RANDFILE from >%s< in >%s<" $rfile $1
    ExecuteAsAdmin $OPENSSL rand -rand $rfile -out $1 2048
 }
 
@@ -405,7 +370,7 @@ MakeRandFile()
 MakeUserCerts()
 {
    if [ ! -f "$1" ]; then
-      Translate 0 "no valid userfile $1. Exit."
+      $INFOTEXT "no valid userfile >%s<. Exit." $1
       exit 1
    fi
 
@@ -413,7 +378,7 @@ MakeUserCerts()
       unixuser=`echo $line|cut -d: -f1`
       gecos=`echo $line|cut -d: -f2`
       email=`echo $line|cut -d: -f3`
-      Translate 0 "Generating certificate and key for '%s' ('%s','%s')." \
+      $INFOTEXT "Generating certificate and key for '%s' ('%s','%s')." \
          "$unixuser" "$gecos" "$email"
       MakeCert user "$unixuser" "$gecos" "$email"
    done   
@@ -429,6 +394,7 @@ MakeUserCerts()
 #
 MakeCert()
 {
+   $INFOTEXT -u "\nCreating '%s' certificate and key" "$3"
 
    TMPFILE=/tmp/sge_ca$$.tmp
    TMPFILE1=/tmp/sge_ca1$$.tmp
@@ -466,7 +432,7 @@ MakeCert()
    # create a certificate request
    ExecuteAsAdmin $REQ -config $TMPFILE1 -new -keyout $KEYFILE -out $REQFILE $DAYS
    if [ $? != 0 ]; then
-      Translate 0 "Can't create %s or %s. Exit." $KEYFILE $REQFILE
+      $INFOTEXT "Can't create %s or %s. Exit." $KEYFILE $REQFILE
       exit 1
    fi  
 
@@ -474,7 +440,7 @@ MakeCert()
    ExecuteAsAdmin $CA -config $TMPFILE1 -policy policy_anything -batch $DAYS \
                       -out $CERTFILE -infiles $REQFILE
    if [ $? != 0 ]; then
-      Translate 0 "Can't sign certificate request %s. Exit." $REQFILE 
+      $INFOTEXT "Can't sign certificate request %s. Exit." $REQFILE 
       exit 1
    fi
    ExecuteAsAdmin $CHMOD 444 $CERTFILE
@@ -482,7 +448,7 @@ MakeCert()
    $RM -f $TMPFILE $TMPFILE1 
 
    if [ $1 = daemon ]; then
-      Translate 0 "created and signed certificate for SGE daemons" 
+      $INFOTEXT "created and signed certificate for SGE daemons" 
    else
       if [ $rootinstalls = true ]; then
          Execute $CHMOD 500 $KEYDIR
@@ -490,7 +456,7 @@ MakeCert()
          Execute $CHOWN -R $2 $KEYDIR
       fi
 
-      Translate 0 "created and signed certificate for user >%s< in >%s<" $2 $KEYDIR
+      $INFOTEXT "created and signed certificate for user >%s< in >%s<" $2 $KEYDIR
    fi
 
    umask 022
@@ -507,14 +473,9 @@ MakeCADirs()
 
 
    if [ -f $CATOP -o -f $CALOCALTOP ]; then
-      Translate 0 "The CA directories"
-      $ECHO
-      Translate 0 "   %s or %s" $CATOP $CALOCALTOP
-      $ECHO
-      Translate 0 "seem to be regular files."
-      $ECHO
-      Translate 0 "CA initialization failed. Exit."
-      $ECHO
+      $INFOTEXT "The CA directories\n   %s or %s\n seem to be regular files" \
+            $CATOP $CALOCALTOP
+      $INFOTEXT "CA initialization failed. Exit."
       exit 1
    fi
 
@@ -522,49 +483,50 @@ MakeCADirs()
    ExecuteAsAdmin $RM -rf $CATOP >/dev/null 2>/dev/null
 
    if [ -f $CATOP -o -d $CATOP -o -f $CALOCALTOP -o -d $CALOCALTOP ]; then
-      Translate 0 "Can't delete the CA directories"
-      $ECHO
-      Translate 0 "   %s or %s" $CATOP $CALOCALTOP
-      $ECHO
-      Translate 0 "CA initialization failed. Exit."
-      $ECHO
+      $INFOTEXT "Can't delete the CA directories\n   %s or %s" \
+            $CATOP $CALOCALTOP
+      $INFOTEXT "CA initialization failed. Exit."
       exit 1
    fi
 
-   Translate 0 "Creating %s" $CATOP
+   $INFOTEXT "Creating %s" $CATOP
    ExecuteAsAdmin $MKDIR $CATOP
 
-   Translate 0 "Creating %s" $CALOCALTOP
+   $INFOTEXT "Creating %s" $CALOCALTOP
    Execute $MKDIR -p $CALOCALTOP
 
    if [ $ADMINUSER != default -a $rootinstalls = true ]; then
       Execute $CHOWN $ADMINUSER $CALOCALTOP
    fi
 
-   Translate 0 "Creating %s" ${CATOP}/certs
+   $INFOTEXT "Creating %s" ${CATOP}/certs
    ExecuteAsAdmin $MKDIR ${CATOP}/certs
 
-   Translate 0 "Creating %s" ${CATOP}/crl
+   $INFOTEXT "Creating %s" ${CATOP}/crl
    ExecuteAsAdmin $MKDIR ${CATOP}/crl
 
-   Translate 0 "Creating %s" ${CATOP}/newcerts
+   $INFOTEXT "Creating %s" ${CATOP}/newcerts
    ExecuteAsAdmin $MKDIR ${CATOP}/newcerts
 
-   Translate 0 "Creating %s" ${CATOP}/serial
+   $INFOTEXT "Creating %s" ${CATOP}/serial
    TruncCreateAndMakeWriteable ${CATOP}/serial
    echo "01" > ${CATOP}/serial
    ExecuteAsAdmin $CHMOD 644 ${CATOP}/serial
 
-   Translate 0 "Creating %s" ${CATOP}/index.txt
+   $INFOTEXT "Creating %s" ${CATOP}/index.txt
    ExecuteAsAdmin $TOUCH ${CATOP}/index.txt   
 
-   Translate 0 "Creating %s" ${CALOCALTOP}/userkeys
+   $INFOTEXT "Creating %s" ${CALOCALTOP}/userkeys
    ExecuteAsAdmin $MKDIR ${CALOCALTOP}/userkeys   
 
    umask 077
-   Translate 0 "Creating %s" ${CALOCALTOP}/private
+   $INFOTEXT "Creating %s" ${CALOCALTOP}/private
    ExecuteAsAdmin $MKDIR ${CALOCALTOP}/private
    umask 022
+
+   $INFOTEXT -wait -auto $autoinst -n "\nHit <RETURN> to continue >> "
+   $CLEAR
+
 }
 
 #--------------------------------------------------------------------------
@@ -578,26 +540,24 @@ MakeCADirs()
 umask 022
 
 if [ -z "$SGE_ROOT" -o ! -d "$SGE_ROOT" ]; then
-   echo
-   echo ERROR: Please set your \$SGE_ROOT environment variable
-   echo and start this script again.
-   echo
+   $INFOTEXT -e \
+      "\nERROR: Please set your \$SGE_ROOT environment variable\n" \
+      "and start this script again.\n"
    exit 1
 fi
 
 if [ ! -f "$SGE_ROOT/util/arch" ]; then
-   echo
-   echo ERROR: The shell script \"$SGE_ROOT/util/arch\" does not exist.
-   echo Please verify your distribution and restart this script.
-   echo
+   $INFOTEXT -e \
+      "ERROR: The shell script \"\$SGE_ROOT/util/arch\" does not exist.\n" \
+      "Please verify your distribution and restart this script.\n"
    exit 1
 fi
 
 if [ ! -f $SGE_ROOT/util/arch_variables ]; then
-   echo
-   echo ERROR: Missing shell script \"$SGE_ROOT/util/arch_variables\".
-   echo Please verify your distribution and restart this script.
-   echo
+   $INFOTEXT -e \
+      "\nERROR: Missing shell script \"\$SGE_ROOT/util/arch_variables\".\n" \
+      "Please verify your distribution and restart this script.\n"
+   
    exit 1
 fi
 
@@ -651,7 +611,7 @@ fi
 ME=`whoami`
 
 if [ "$ME" = "" ]; then
-   Translate 0 "Can't determine your username with \"%s\" command. Exit" whoami
+   $INFOTEXT "Can't determine your username with \"%s\" command. Exit" whoami
    exit 1
 fi
 
@@ -660,6 +620,24 @@ CACERT=cacert.pem
 
 CONFIG_DIR=$SGE_ROOT/util/sgeCA
 OPENSSL=$V5UTILBIN/openssl
+
+# set to false if you don't want this script uses the i18n functions
+#
+SGE_INFOTEXT_MAX_COLUMN=500; export SGE_INFOTEXT_MAX_COLUMN
+
+#-----------------------------
+# setup INFOTEXT
+#-----------------------------
+INFOTEXT=$V5UTILBIN/infotext
+INFOTXT_DUMMY=$V5UTILBIN/infotext
+if [ ! -f $INFOTXT_DUMMY ]; then
+   $ECHO "can't find \"$INFOTXT_DUMMY\""
+   $ECHO "Installation failed."
+   exit 1
+fi
+
+
+
 
 #-----------------------------
 # CommandLine Argument Parsing
@@ -691,8 +669,7 @@ while [ $ARGC != 0 ]; do
       ;;
    -days)
       if [ $ARGC -lt 2 ]; then
-         $ECHO "" >&2
-         Translate "Error: -days needs argument" 2 1
+         $INFOTEXT "Error: -days needs argument"
          ErrUsage
       fi
       DAYS="-days $2"
@@ -702,8 +679,7 @@ while [ $ARGC != 0 ]; do
    -usercert)
       WHICH="usercert"
       if [ $ARGC -lt 2 ]; then
-         $ECHO "" >&2
-         Translate "Error: -usercert needs argument" 2 1
+         $INFOTEXT "Error: -usercert needs argument"
          ErrUsage
       fi
       userfile=$2
@@ -711,8 +687,7 @@ while [ $ARGC != 0 ]; do
       ARGC=`expr $ARGC - 1`
       ;;
    *)
-      $ECHO "" >&2
-      Translate "Error: Unknown option %s" 2 1 "$1"
+      $INFOTEXT "Error: Unknown option %s" "$1"
       ErrUsage
       ;;
    esac
@@ -743,16 +718,16 @@ req)
     $REQ -new -keyout $outdir/$newreq -out $outdir/$newreq $DAYS
     RET=$?
     if [ $RET = 0 ]; then
-      echo "Request (and private key) is in $outdir/$newreq"
+      $INFOTEXT "Request (and private key) is in %s" $outdir/$newreq
     else
-      echo "No success"
+      $INFOTEXT "No success"
     fi  
    ;;
 sign) 
     $CA -policy policy_anything $DAYS $BATCHMODE -out $outdir/$newcert -infiles $indir/$newreq
     RET=$?
     if [ $RET = 0 ]; then
-      echo "Signed certificate is in $outdir/$newcert"
+      $INFOTEXT "Signed certificate is in %s" $outdir/$newcert
     fi
     ;;
 copy) 
