AS-2002-0808-0 cleanup in i18n setup

diff --git a/source/dist/util/sgeCA/sge_ca b/source/dist/util/sgeCA/sge_ca
--- a/source/dist/util/sgeCA/sge_ca
+++ b/source/dist/util/sgeCA/sge_ca
@@ -532,31 +532,29 @@ MakeCADirs()
 # THE MAIN PROCEDURE
 #--------------------------------------------------------------------------
 
-#----------------------------------
-# GET ARCH + ARCH SPECIFIC DEFAULTS
-#
-
 umask 022
 
 if [ -z "$SGE_ROOT" -o ! -d "$SGE_ROOT" ]; then
-   $INFOTEXT -e \
-      "\nERROR: Please set your \$SGE_ROOT environment variable\n" \
-      "and start this script again.\n"
+   echo
+   echo ERROR: Please set your \$SGE_ROOT environment variable
+   echo and start this script again. Exit.
+   echo
    exit 1
 fi
 
 if [ ! -f "$SGE_ROOT/util/arch" ]; then
-   $INFOTEXT -e \
-      "ERROR: The shell script \"\$SGE_ROOT/util/arch\" does not exist.\n" \
-      "Please verify your distribution and restart this script.\n"
+   echo
+   echo ERROR: The shell script \"$SGE_ROOT/util/arch\" does not exist.
+   echo Please verify your distribution and restart this script. Exit.
+   echo
    exit 1
 fi
 
 if [ ! -f $SGE_ROOT/util/arch_variables ]; then
-   $INFOTEXT -e \
-      "\nERROR: Missing shell script \"\$SGE_ROOT/util/arch_variables\".\n" \
-      "Please verify your distribution and restart this script.\n"
-   
+   echo
+   echo ERROR: Missing shell script \"$SGE_ROOT/util/arch_variables\".
+   echo Please verify your distribution and restart this script. Exit.
+   echo
    exit 1
 fi
 
@@ -572,29 +570,26 @@ else
    CA_PORT=sge_commd
 fi
 
-#-------------------------------------------------------------------------
-# setup i18n
 
-if [ "$GETTEXT" != "" -a "SGE_I18N" = true ]; then
-   unset TEXTDOMAINDIR TEXTDOMAIN
-   TEXTDOMAINDIR="`/bin/pwd`/locale"
-   TEXTDOMAIN=gridengine
-   translation=1
-else
-   translation=0
-   unset LANG LC_ALL LC_COLLATE LC_CTYPE LC_MESSAGES LC_MONETARY
-   unset LC_NUMERIC LC_TIME LANGUAGE
-fi
-
-# end of internationalization setup
-#-------------------------------------------------------------------------
-
-# Set variable $ADMINUSER
-#
-SetAdminUser
+#---------------------------------------
+# setup INFOTEXT begin
+#---------------------------------------
 
 V5BIN=$SGE_ROOT/bin/$ARCH
 V5UTILBIN=$SGE_ROOT/utilbin/$ARCH
+INFOTEXT=$V5UTILBIN/infotext
+if [ ! -x $INFOTEXT ]; then
+   echo "can't find binary \"$INFOTXT\""
+   echo "Installation failed."
+   exit 1
+fi
+SGE_INFOTEXT_MAX_COLUMN=5000; export SGE_INFOTEXT_MAX_COLUMN
+
+#---------------------------------------
+# setup INFOTEXT end
+#---------------------------------------
+
+SetAdminUser
 
 CATOP=$SGE_ROOT/$SGE_CELL/common/sgeCA
 
@@ -608,7 +603,6 @@ else
 fi
 
 ME=`whoami`
-
 if [ "$ME" = "" ]; then
    $INFOTEXT "Can't determine your username with \"%s\" command. Exit" whoami
    exit 1
@@ -619,35 +613,6 @@ CACERT=cacert.pem
 
 CONFIG_DIR=$SGE_ROOT/util/sgeCA
 OPENSSL=$V5UTILBIN/openssl
-
-
-#---------------------------------------
-# setup INFOTEXT begin
-#---------------------------------------
-
-# set column break for automatic line break 
-SGE_INFOTEXT_MAX_COLUMN=5000; export SGE_INFOTEXT_MAX_COLUMN
-
-# export locale directory 
-if [ "$SGE_ROOT" = "" ]; then 
-   TMP_SGE_ROOT=`pwd | sed 's/\/tmp_mnt//'`
-   GRIDLOCALEDIR="$TMP_SGE_ROOT/locale"
-   export GRIDLOCALEDIR
-fi
-
-# set infotext binary path
-INFOTXT_DUMMY=$V5UTILBIN/infotext
-INFOTEXT=$INFOTXT_DUMMY
-if [ ! -f $INFOTXT_DUMMY ]; then
-   $ECHO "can't find \"$INFOTXT_DUMMY\""
-   $ECHO "Installation failed."
-   exit 1
-fi
-#---------------------------------------
-# setup INFOTEXT end
-#---------------------------------------
-
-
 
 #-----------------------------
 # CommandLine Argument Parsing
