MD-2005-01-31-0: Bugfix:    distinst assumes certain files always exist                  Issue:     1361                  Review:    AS

diff --git a/source/scripts/distinst b/source/scripts/distinst
--- a/source/scripts/distinst
+++ b/source/scripts/distinst
@@ -47,10 +47,12 @@ DEFAULTPROG="sge_qmaster sge_execd sge_shadowd sge_schedd \
 UTILITYBINARIES="uidgid gethostname gethostbyname gethostbyaddr \
                  getservbyname filestat checkprog loadcheck now checkuser \
                  adminrun qrsh_starter testsuidroot \
-                 sge_share_mon openssl infotext \
-                 spooldefaults spooledit spoolinit \
-                 berkeley_db_svc db_dump db_load db_archive db_checkpoint \
+                 sge_share_mon infotext spooldefaults spooledit spoolinit \
                  fstype"
+
+BDBUTILITYBINARIES="berkeley_db_svc db_dump db_load db_archive db_checkpoint"
+
+SSLUTILITYBINARIES="openssl"
 
 REMOTEBINARIES="rsh rshd rlogin"
 
@@ -69,7 +71,7 @@ BERKELEYDB_SHARED_LIBRARIES="libdb-4.2"
 
 DRMAA_SHARED_LIBRARIES="libdrmaa"
 DRMAA_HEADER_FILES="libs/japi/drmaa.h"
-DRMAAJ_FILES="../CLASSES/drmaa.jar"
+DRMAAJ_FILES="CLASSES/drmaa.jar"
 
 PVMSOURCES="start_pvm.c stop_pvm.c slave.c master.c spmd.c Makefile"
 PVMSRCSCRIPTS="install.sh aimk"
@@ -113,8 +115,10 @@ ErrUsage()
    echo "       -libs          = all libraries"
    echo "       -local         = install in \$SGE_ROOT"
    echo "       -mansrc <dir>  = take man pages from MANSBUILD_<dir>"
+   echo "       -nobdb         = do not install the Berkeley DB binaries and libs"
    echo "       -noexit        = do not exit on installation errors"
    echo "       -noinst        = no install, show target arch"
+   echo "       -noopenssl     = do not install the OpenSSL binaries and libs"
    echo "       -nosource      = do not source \"distinst.private\""
    echo "       -onlybin       = all binaries, no libraries"
    echo "       -classic-targets = qmaster+spool* from <ARCHDIR>_classic"
@@ -464,6 +468,8 @@ instsec=false
 instsecbin=false
 inst3rdparty=false
 instclassictargets=false
+instopenssl=true
+instbdb=true
 
 cmdname=`basename $0`
 
@@ -578,12 +584,18 @@ while [ $# -ge 1 ]; do
          exit 1
       fi
       ;;
+   -nobdb)
+      instbdb=false
+      ;;
    -noexit)
       exit_on_error=false
       ;;
    -noinst)
       PROG="$DEFAULTPROG"
       INSTOPT="noinst"
+      ;;
+   -noopenssl)
+      instopenssl=false
       ;;
    -v)
       verbose=true
@@ -612,6 +624,15 @@ while [ $# -ge 1 ]; do
    esac
    shift
 done
+
+if [ $instbdb = true ]; then
+   UTILITYBINARIES="$UTILITYBINARIES $BDBUTILITYBINARIES"
+fi
+
+if [ $instopenssl = true ]; then
+   UTILITYBINARIES="$UTILITYBINARIES $SSLUTILITYBINARIES"
+fi
+
 
 if [ $localinst = false ]; then
    if [ $BASEDIR = undefined ]; then
@@ -934,6 +955,15 @@ if [ $instcommon = true ]; then
       for f in $DRMAA_HEADER_FILES; do
          Execute cp $f $DEST_SGE_ROOT/include
       done
+
+      for filename in $DRMAAJ_FILES; do
+         if [ -f $filename ]; then
+             echo Installing `basename $filename`
+             Execute rm -f $DEST_SGE_ROOT/lib/`basename $filename`
+             MakeDir lib
+             Install 0.0 755 $filename $DEST_SGE_ROOT/lib
+         fi
+      done
       Cleanup include
    fi
 
@@ -984,7 +1014,9 @@ if [ $instcommon = true ]; then
       echo Installing \"man/\" and \"catman/\"
       Execute rm -rf $DEST_SGE_ROOT/man $DEST_SGE_ROOT/catman
       Execute cp -r MANSBUILD_$MANSRCDIR/SEDMAN/man $DEST_SGE_ROOT
-      Execute cp -r MANSBUILD_$MANSRCDIR/ASCMAN/catman $DEST_SGE_ROOT
+      if [ -d MANSBUILD_$MANSRCDIR/ASCMAN/catman ]; then
+         Execute cp -r MANSBUILD_$MANSRCDIR/ASCMAN/catman $DEST_SGE_ROOT
+      fi
       Cleanup man catman
    fi
 
@@ -1250,40 +1282,45 @@ for i in $ARCH; do
             fi
          done
 
-         for lib in $OPENSSL_SHARED_LIBRARIES; do
-            if [ $DSTARCH = tru64 ]; then
-               libname="$OPENSSLBASE/$DSTARCH/lib/$lib.$shlibext"
-            elif [ $DSTARCH = darwin ];  then
-               libname="$OPENSSLBASE/$DSTARCH/lib/$lib.0.9.7.$shlibext"
-            else
-               libname="$OPENSSLBASE/$DSTARCH/lib/$lib.$shlibext.0.9.7"
-            fi
-            if [ -f $libname ]; then
-               InstallProg $libname
-               if [ $DSTARCH = tru64 ]; then
-                  :
-               elif [ $DSTARCH = darwin ]; then
-                  (cd $DEST_SGE_ROOT/${UTILPREFIX}/$DSTARCH; \
-                   ln -s $lib.0.9.7.$shlibext $lib.$shlibext)
-               else
-                  (cd $DEST_SGE_ROOT/${UTILPREFIX}/$DSTARCH; ln -s $lib.${shlibext}.0.9.7 $lib.$shlibext)
-               fi
-               
-            elif [ $exit_on_error = true ]; then
-               echo "\"$libname\" not found. Installation failed."
-               exit 1
-            fi
-         done
+         if [ $instopenssl = true ]; then
+            for lib in $OPENSSL_SHARED_LIBRARIES; do
 
-         for lib in $BERKELEYDB_SHARED_LIBRARIES; do
-            libname="$BERKELEYDBBASE/$DSTARCH/lib/$lib.$shlibext"
-            if [ -f $libname ]; then
-               InstallProg $libname
-            elif [ $exit_on_error = true ]; then
-               echo "\"$libname\" not found. Installation failed."
-                exit 1
-            fi
-         done
+               if [ $DSTARCH = tru64 ]; then
+                  libname="$OPENSSLBASE/$DSTARCH/lib/$lib.$shlibext"
+               elif [ $DSTARCH = darwin ];  then
+                  libname="$OPENSSLBASE/$DSTARCH/lib/$lib.0.9.7.$shlibext"
+               else
+                  libname="$OPENSSLBASE/$DSTARCH/lib/$lib.$shlibext.0.9.7"
+               fi
+
+               if [ -f $libname ]; then
+                  InstallProg $libname
+                  if [ $DSTARCH = tru64 ]; then
+                     :
+                  elif [ $DSTARCH = darwin ]; then
+                     (cd $DEST_SGE_ROOT/${UTILPREFIX}/$DSTARCH; \
+                      ln -s $lib.0.9.7.$shlibext $lib.$shlibext)
+                  else
+                     (cd $DEST_SGE_ROOT/${UTILPREFIX}/$DSTARCH; ln -s $lib.${shlibext}.0.9.7 $lib.$shlibext)
+                  fi
+               elif [ $exit_on_error = true ]; then
+                  echo "\"$libname\" not found. Installation failed."
+                  exit 1
+               fi
+            done
+         fi
+
+         if [ $instbdb = true ]; then
+            for lib in $BERKELEYDB_SHARED_LIBRARIES; do
+               libname="$BERKELEYDBBASE/$DSTARCH/lib/$lib.$shlibext"
+               if [ -f $libname ]; then
+                  InstallProg $libname
+               elif [ $exit_on_error = true ]; then
+                  echo "\"$libname\" not found. Installation failed."
+                  exit 1
+               fi
+            done
+         fi
 
          for lib in $DRMAA_SHARED_LIBRARIES; do
             libname=$lib.$shlibext
@@ -1304,14 +1341,6 @@ for i in $ARCH; do
 
             ln -s $DEST_SGE_ROOT/lib/$DSTARCH/$lib.$shlibext $DEST_SGE_ROOT/lib/$DSTARCH/$lib.$jnilibext
          fi
-
-         for filename in $DRMAAJ_FILES; do
-            if [ -f $filename ]; then
-                echo Installing `basename $filename`
-                Execute rm -f $DEST_SGE_ROOT/lib/`basename $filename`
-                Install 0.0 755 $filename $DEST_SGE_ROOT/lib
-            fi
-         done
       fi
       cd ..
    fi     
