RD-2005-07-01-0: Bugfix:   distinst ignored sgepasswd                            and tried to copy libXltree on win32-x86                            sgepasswd not covered by setfileperm.sh                  Changed:  setfileperm.sh, distinst                  Review:   JG, CR

diff --git a/source/scripts/distinst b/source/scripts/distinst
--- a/source/scripts/distinst
+++ b/source/scripts/distinst
@@ -1308,12 +1308,14 @@ for i in $ARCH; do
          done
 
          for lib in $QMON_NEED_SHARED_LIBRARIES; do
-            libname="../3rdparty/qmon/$ARCHBIN/$lib.$shlibext"
-            if [ -f $libname ]; then
-               InstallProg $libname
-            elif [ $exit_on_error = true ]; then
-               echo "\"$libname\" not found. Installation failed."
-               exit 1
+            if [ "$DSTARCH" != "win32-x86" ]; then
+               libname="../3rdparty/qmon/$ARCHBIN/$lib.$shlibext"
+               if [ -f $libname ]; then
+                  InstallProg $libname
+               elif [ $exit_on_error = true ]; then
+                  echo "\"$libname\" not found. Installation failed."
+                  exit 1
+               fi
             fi
          done
 
