RD-2005-07-01-0: Bugfix     distinst ignored sgepasswd                             and tried to copy libXltree on win32-x86                  Changed:   distinst                  Review:    JG

diff --git a/source/scripts/distinst b/source/scripts/distinst
--- a/source/scripts/distinst
+++ b/source/scripts/distinst
@@ -43,7 +43,7 @@ HASARCHDIR="bin lib examples/jobsbin utilbin"
 DEFAULTPROG="sge_qmaster sge_execd sge_shadowd sge_schedd \
              sge_shepherd sge_coshepherd qstat qsub qalter qconf qdel \
              qacct qmod qsh utilbin jobs qmon qhost qmake qtcsh qping \
-             qloadsensor.exe"
+             qloadsensor.exe sgepasswd"
 
 UTILITYBINARIES="uidgid gethostname gethostbyname gethostbyaddr \
                  getservbyname filestat checkprog loadcheck now checkuser \
@@ -1308,12 +1308,14 @@ for i in $ARCH; do
          done
 
          for lib in $QMON_NEED_SHARED_LIBRARIES; do
-            libname="../3rdparty/qmon/$ARCHBIN/$lib.$shlibext"
-            if [ -f $libname ]; then
-               InstallProg $libname
-            elif [ $exit_on_error = true ]; then
-               echo "\"$libname\" not found. Installation failed."
-               exit 1
+            if [ "$DSTARCH" != "win32-x86" ]; then
+               libname="../3rdparty/qmon/$ARCHBIN/$lib.$shlibext"
+               if [ -f $libname ]; then
+                  InstallProg $libname
+               elif [ $exit_on_error = true ]; then
+                  echo "\"$libname\" not found. Installation failed."
+                  exit 1
+               fi
             fi
          done
 
