AS-2002-07-18-0 installation changes, version set to beta3

diff --git a/source/scripts/distinst b/source/scripts/distinst
--- a/source/scripts/distinst
+++ b/source/scripts/distinst
@@ -335,6 +335,7 @@ inst3rdparty=false
 
 exit_on_error=true
 sgeee=false
+sundist=false
 localinst=false
 setfileperm=true
 
@@ -359,14 +360,16 @@ elif [ $cmdname = myinst ]; then
 elif [ $cmdname = sgeinst ]; then 
    # This special rule creates a distribution which will be provided by Sun
    BASEDIR=/dist/SGEDIST
-   VERSIONDIR=SGE53p1
+   VERSIONDIR=SGE531beta2
    SGE_PRODUCT_MODE=sge
+   sundist=true
 elif [ $cmdname = sgeeeinst ]; then
    # This special rule creates a distribution which will be provided by Sun
    BASEDIR=/dist/SGEDIST
-   VERSIONDIR=SGEEE53p1
+   VERSIONDIR=SGEEE531beta2
    SGE_PRODUCT_MODE=sgeee
    sgeee=true
+   sundist=true
 else
    echo echo Unsupported command name: $cmdname.
    echo
@@ -466,6 +469,10 @@ if [ $localinst = false ]; then
    fi
 
    DEST_SGE_ROOT=$BASEDIR/$VERSIONDIR
+   if [ -f $DEST_SGE_ROOT/LOCKED ]; then
+      echo "Sorry, file \"$DEST_SGE_ROOT/LOCKED\" exits. Installation failed."
+      exit 1
+   fi
    mkdir -p $DEST_SGE_ROOT
 fi
 
@@ -680,10 +687,17 @@ if [ $instcommon = true ]; then
       Execute chmod 644 $DEST_SGE_ROOT/qmon/PIXMAPS/*.xpm
       Execute chmod 644 $DEST_SGE_ROOT/qmon/PIXMAPS/big/*.xpm
 
-      Execute cp dist/qmon/Qmon $DEST_SGE_ROOT/qmon/Qmon
+      Execute cp dist/qmon/Qmon $DEST_SGE_ROOT/qmon
+      Execute cp dist/qmon/Qmon.i18n $DEST_SGE_ROOT/qmon
       Execute chmod 644 $DEST_SGE_ROOT/qmon/Qmon
+      Execute chmod 644 $DEST_SGE_ROOT/qmon/Qmon.i18n
    
-      Execute cp dist/qmon/qmon_help.ad $DEST_SGE_ROOT/qmon
+      Execute scripts/sed_help
+      if [ $sgeee = false ]; then
+         Execute cp dist/qmon/qmon_help.ad.ge $DEST_SGE_ROOT/qmon/qmon_help.ad
+      else
+         Execute cp dist/qmon/qmon_help.ad.geee $DEST_SGE_ROOT/qmon/qmon_help.ad
+      fi
       Execute chmod 644 $DEST_SGE_ROOT/qmon/qmon_help.ad
 
       ( echo changing to $DEST_SGE_ROOT/qmon/PIXMAPS ; \
@@ -813,6 +827,10 @@ if [ $instcommon = true ]; then
    if [ $setfileperm = true ]; then
       echo Setting file permissions
       SetFilePerm $DEST_SGE_ROOT
+   fi
+
+   if [ $sundist = true ]; then
+      touch $DEST_SGE_ROOT/.COMMON_CHANGED
    fi
 
    # Remove CVS directories, ".#" files, backup files
@@ -963,7 +981,7 @@ for i in $ARCH; do
 
       for lib in $QMON_SHARED_LIBRARIES; do
          libname="../3rdparty/qmon/$ARCHBIN/$lib.$shlibext"
-         echo checking $libname
+         # echo checking $libname
          if [ -f $libname ]; then
             InstallProg $libname
          fi
@@ -971,7 +989,7 @@ for i in $ARCH; do
 
       for lib in $ZLIB_SHARED_LIBRARIES; do
          libname="../3rdparty/zlib/$ARCHBIN/$lib.$shlibext"
-         echo checking $libname
+         # echo checking $libname
          if [ -f $libname ]; then
             InstallProg $libname
          fi
