LP-2008-07-04-0: Enhancem:  Windows host list is now saved during the backup for                             upgrade procedure                  Enhancem:  SGE_CELL, SGE_CLUSTER_NAME, PRODUCT_MODE is used                             from the backup during the upgrade                  Enhancem:  Added post update actions to clean execd_spool_dirs,                             remove RC scripts, create RC scripts, update WINSVC                  Enhancem:  COPY_COMMAND is only checked when CSP_COPY_CERTS=true                  Enhancem:  WINSVC install no longer reinstalls a service                             (winupdate should be used)                  Cleanup:   Various upgrade/install code                  Bugfix:    Removed "No CSP system installed!" during qmaster                             installation (without CSP)                  Bugfix:    JMX java detection fixed                  Bugfix:    Upgrade script failed when choosing a different                             port number then $SGE_QMASTER_PORT                  Bugfix:    upgrade does not create arusers user set                  Bugfix:    upgrade does not save host_aliases file                  Bugfix:    upgrade does not create display_win_gui complex                  Bugster:   6717816, 6722652, 6722805, 6722806                  Review:    AP

diff --git a/source/dist/inst_sge b/source/dist/inst_sge
--- a/source/dist/inst_sge
+++ b/source/dist/inst_sge
@@ -64,7 +64,6 @@ PWD=`pwd`
 #---------------------------------------
 
 UPDATE=false
-UPDATEDB=false
 DOWNGRADE=false
 BACKUP=false
 RESTORE=false
@@ -77,9 +76,14 @@ AFS=false
 NOREMOTE=false
 START_RPC_SERVICE=false
 ADD_TO_RC=false
-REMOVE_RC=false
 SET_FILE_PERMS=false
 MAKE_RC=false
+ADD_RC=false
+REMOVE_RC=false
+UPDATE_RC=false
+UPDATE_WIN=false
+DEL_EXECD_SPOOL=false
+POST_UPDATE=false
 WIN_UPDATE=false
 COPY_CA="false"
 RECREATE_SETTINGS="false"
@@ -149,7 +153,6 @@ while [ $ARGC != 0 ]; do
      shift
      ARGC=`expr $ARGC - 1`
      #Stdout2Log
-     GetConfigFromFile
      CheckPath
      ;;
    -m)
@@ -237,6 +240,29 @@ while [ $ARGC != 0 ]; do
      . ./util/install_modules/inst_st.sh
      . ./util/upgrade_modules/inst_upgrade.sh
      ;;
+   -post-upd)
+     POST_UPDATE=true
+     . ./util/install_modules/inst_common.sh
+     . ./util/upgrade_modules/inst_upgrade.sh
+     ;;
+   -upd-execds)
+     ALL_RC=true
+     DEL_EXECD_SPOOL=true
+     . ./util/install_modules/inst_common.sh
+     . ./util/upgrade_modules/inst_upgrade.sh
+     ;;
+   -upd-win)
+     UPDATE_WIN=true
+     . ./util/install_modules/inst_common.sh
+     . ./util/upgrade_modules/inst_upgrade.sh
+     ;;
+   -upd-rc)
+     UPDATE_RC=true
+     ALL_RC=true
+     RC_VERSION="61"
+     REMOVE_RC=true
+     ADD_RC=true
+     ;;
    -winupdate)
      #update to new Gridengine Helper Service
      WIN_UPDATE="true"
@@ -248,17 +274,41 @@ while [ $ARGC != 0 ]; do
      WIN_SVC="install"
      . ./util/install_modules/inst_common.sh
      . ./util/install_modules/inst_execd.sh
-    ;;
+     ;;
    -uwinsvc)
      #uninstall the windows helper service only
      WIN_SVC="uninstall"
      . ./util/install_modules/inst_common.sh
      . ./util/install_modules/inst_execd.sh
-    ;;
+     ;;
    -rccreate)
      MAKE_RC=true
      #Generate new rc scripts from settings file
-     ;; 
+     ;;
+   -rc-remove-execd-61)
+     HOST_TYPE=execd
+     RC_VERSION="61"
+     REMOVE_RC=true
+     if [ "$2" = "all" ]; then
+        ALL_RC="true"
+        shift
+	ARGC=`expr $ARGC - 1`
+     else
+        RC_HOST_LIST="$2"
+     fi
+     ;;
+   -rc-remove-execd)
+     HOST_TYPE=execd
+     RC_VERSION=""
+     REMOVE_RC=true
+     if [ "$2" = "all" ]; then
+        ALL_RC="true"
+        shift
+	ARGC=`expr $ARGC - 1`
+     else
+        RC_HOST_LIST="$2"
+     fi
+     ;;
    -noremote)
      NOREMOTE=true
      #Disable remote installation
@@ -322,16 +372,13 @@ if [ $AUTO = "false" -a $QMASTER = "undef" -a $EXECD = "install" -a $SHADOW = "i
    ErrUsage
 fi
 
-#CR 6692104: can not combine 'inst_sge -x' and 'install_execd' with -winsvc switch
-if [ $EXECD = "install" -a WIN_SVC = "install" ]; then
-   ErrUsage
-fi
 
 #checking the autoinstall configuration file at this point of installation,
 #because the commandline switches are completely parsed and we know the selected options.
 #This will influence the configfile parsing and checking mechanism.
 if [ $AUTO = "true" ]; then
    CheckConfigFile $FILE
+   GetConfigFromFile
 fi
 
 $CLEAR
@@ -345,19 +392,19 @@ if [ $USE_OLD_IJS = "false" ]; then
    RSH_COMMAND="builtin"
 fi
 
-if [ $WIN_UPDATE = "true" ]; then
+if [ "$WIN_UPDATE" = "true" ]; then
    WelcomeTheUserWinUpdate
    SetupWinSvc update #service install due to an update -> param: update
    # don't exit but continue with installation of execution daemon
 fi
 
-if [ $WIN_SVC = "install" ]; then
+if [ "$WIN_SVC" = "install" ]; then
    WelcomeTheUserWinSvc install #install text param
    SetupWinSvc install #service install due to service install switch -> param install
    # don't exit but continue with installation of execution daemon
 fi
 
-if [ $WIN_SVC = "uninstall" ]; then
+if [ "$WIN_SVC" = "uninstall" ]; then
    WelcomeTheUserWinSvc uninstall #uninstall text param
    SetupWinSvc uninstall #service install due to service uninstall switch -> param uninstall
    # don't exit but continue with uninstallation of execution daemon
@@ -377,7 +424,7 @@ if [ "$UPDATE" = true ]; then
    GetBackupDirectory
    #Old rc scripts must be long gone!
    
-   #Source sge_root. sge_cell, qmaster, execd port from the backup
+   #Source sge_root, sge_cell, qmaster, execd port from the backup
    SGE_ROOT=`pwd | sed 's/\/tmp_mnt//'`
    bck_sge_root=`cat "${UPGRADE_BACKUP_DIR}/sge_root" | awk -F= '{print $2}' | awk -F\; '{print $1}' 2>/dev/null`
    . "${UPGRADE_BACKUP_DIR}/sge_cell"
@@ -386,8 +433,10 @@ if [ "$UPDATE" = true ]; then
    CheckForLocalHostResolving
    ProcessSGERoot
    QMASTER=undef
+   SGE_CELL=$bck_sge_cell              #to get sge_cell backup value as default
    GetCell
    QMASTER=install
+   euid=`$SGE_UTILBIN/uidgid -euid`
    #Real upgrade from 6.0+ to 6.2 from here (same SGE_ROOT,SGE_CELL)
    if [ "$SGE_ROOT" = "$bck_sge_root" -a "$SGE_CELL" = "$bck_sge_cell" ]; then
       UPGRADE_MODE="upgrade"
@@ -398,12 +447,17 @@ if [ "$UPDATE" = true ]; then
          $INFOTEXT "Upgrade must be started on a qmaster host!"
          exit 1
       fi
+      if [ ! -f "$SGE_ROOT/$SGE_CELL/common/bootstrap" ]; then
+         $INFOTEXT -n "Cannot continue with the \"real\" upgrade. Installation corrupted.\n" \
+                      "Missing bootstrapfile in %s directory!\n" \
+                      "Rerun the upgrade and choose different value for <sge_root> and/or <sge_cell>.\n" "$SGE_ROOT/$SGE_CELL/common"
+         exit 1
+      fi
    elif [ -f "$SGE_ROOT/$SGE_CELL/common/bootstrap" ]; then
-      $INFOTEXT -n "Bootstrap file exists in selected <sge_root>/<sge_cell> \n" \
-                   "and is not the same as in the backup.\n"\
+      $INFOTEXT -n "Bootstrap file already exists in selected <sge_root>/<sge_cell>.\n" \
                    "If you want to copy the configuration to this location, delete \n" \
-                   "$SGE_ROOT/$SGE_CELL directory \n" \
-                   "and restart the upgrade.\n"
+                   "%s directory \n" \
+                   "and restart the upgrade.\n" "$SGE_ROOT/$SGE_CELL"
       exit 1
    else
       #Just copy the configuration to a new SGE_CELL
@@ -420,7 +474,7 @@ if [ "$UPDATE" = true ]; then
       #Get backuped admin user
       GetBackupedAdminUser
       OLD_ADMIN_USER=$ADMIN_USER
-      GetAdminUser #Get current admin user of the cluster
+      GetAdminUser     #Get current admin user of the cluster
       CheckUpgradeUser #Stop if admin user mismatch (backup vs. current cluster)
       #Detect spool dir from the backup
       QMDIR=`BootstrapGetValue $SGE_ROOT/$SGE_CELL/common "qmaster_spool_dir"`
@@ -428,36 +482,54 @@ if [ "$UPDATE" = true ]; then
       CheckWhoInstallsSGE
       #Ask for new QMaster spool dir
       GetQmasterSpoolDir $euid
-      SGE_CLUSTER_NAME=""     #delete environment
    fi		
    #TODO: Check if no jobs. qmaster.pid?
-   #Need to remove cluster_name if present
-   if [ -f  "$SGE_ROOT/$SGE_CELL/common/cluster_name" ]; then
-      #Need to remove cluster_name if present
-      SGE_CLUSTER_NAME=`cat "$SGE_ROOT/$SGE_CELL/common/cluster_name" 2>/dev/null`
-      ExecuteAsAdmin rm -f "$SGE_ROOT/$SGE_CELL/common/cluster_name"
-   elif [ "$UPGRADE" = upgrade -a -f "$UPGRADE_BACKUP_DIR/cell/cluster_name" ]; then
+   SGE_CLUSTER_NAME=`cat "$SGE_ROOT/$SGE_CELL/common/cluster_name" 2>/dev/null`
+   if [ -z "$SGE_CLUSTER_NAME" -a -f "$UPGRADE_BACKUP_DIR/cell/cluster_name" ]; then
       SGE_CLUSTER_NAME=`cat "$UPGRADE_BACKUP_DIR/cell/cluster_name" 2>/dev/null`
    fi
-   ProcessSGEClusterName qmaster
-   WindowsSupport
-   #UninstWinHelperPre62 #Can we always try to remove it? What about 6.1 and 6.2 on the same host?
-   #SetupWinSvc "update" #run only on all exechosts
-   SetPermissions
    if [ "$UPGRADE_MODE" = copy ]; then
-      #SelectHostNameResolving
+      if [ -f  "$SGE_ROOT/$SGE_CELL/common/cluster_name" ]; then
+         ExecuteAsAdmin rm -f "$SGE_ROOT/$SGE_CELL/common/cluster_name"
+      fi
+      SGE_CLUSTER_NAME=""     #delete environment, we want a new default
+   fi
+   
+   if [ -z "$SGE_CLUSTER_NAME" ]; then
+      ProcessSGEClusterName qmaster
+   fi
+   if [ -f "$UPGRADE_BACKUP_DIR/win_hosts" ]; then
+      WINDOWS_SUPPORT=true
+      WindowsDomainUserAccess
+      ExecuteAsAdmin cp "$UPGRADE_BACKUP_DIR/win_hosts" "$SGE_ROOT/$SGE_CELL/win_hosts_to_update"
+   fi
+   SetPermissions
+   #Detect the product mode
+   PRODUCT_MODE=`BootstrapGetValue ${UPGRADE_BACKUP_DIR}/cell "security_mode"`
+   if [ "$UPGRADE_MODE" = "copy" ]; then
+      case $PRODUCT_MODE in
+         csp)
+            CSP=true
+            ;;
+         afs)
+            AFS=true
+            ;;
+      esac
       SetProductMode
    else
-      PRODUCT_MODE=`BootstrapGetValue $SGE_ROOT/$SGE_CELL/common "security_mode"`
-      #TODO: csp and changed qmaster port needs -csp flag
+      #We don't care about switches, setup is going to be reused
+      CSP=false
+      AFS=false
    fi
    #Find out if jmx should be used from the backup
    RestoreJMX "${UPGRADE_BACKUP_DIR}/cell/jmx"
    #Load and upgrade old cell
    RestoreCell "${UPGRADE_BACKUP_DIR}/cell"
    GetJMXPort
-   ExecuteAsAdmin rm -rf "$QMDIR"   # remove old qmaster spool dir
-   Makedir $QMDIR/job_scripts       # create a new one
+   if [ -d "$QMDIR" ]; then
+      ExecuteAsAdmin rm -rf "$QMDIR/*"   # remove old qmaster spool dir
+   fi
+   Makedir $QMDIR/job_scripts            # create a new one
 
    if [ "$UPGRADE_MODE" = upgrade ]; then
       SelectNewSpooling `BootstrapGetValue "${UPGRADE_BACKUP_DIR}/cell" "spooling_method"`
@@ -469,7 +541,6 @@ if [ "$UPDATE" = true ]; then
    fi
    InitSpoolingDatabase
    ServiceTagsSupport
-   #IJS
    SavedOrNewIJS
    AddDummyConfiguration     #Create a new configuration to be able to start qmaster
    AddActQmaster             #Always overwrite backup settings with current host
@@ -488,24 +559,94 @@ if [ "$UPDATE" = true ]; then
    InitCA
    SetupRcScriptNames master #New qmaster RC script/SMF
    InstallRcScript
-   CopyCA execd
-   CopyCA submit
    #TODO: Need to ensure there is no qmaster on the same port running
    StartQmaster
+   CopyCA execd
+   CopyCA submit
    CheckRunningDaemon sge_qmaster
    $INFOTEXT -u "Last step - load configuration from the backup"
    $INFOTEXT -n "\nload command: $SGE_ROOT/util/upgrade_modules/load_cc.sh $UPGRADE_BACKUP_DIR \n" \
-                "-log C -newijs $newIJS -gid_range $CFG_GID_RANGE -admin_mail $CFG_MAIL_ADDR \n" \
-                "-execd_spool_dir $CFG_EXE_SPOOL \n"   
+             "-log C -newijs \"$newIJS\" -gid_range \"${CFG_GID_RANGE}\" -admin_mail \"${CFG_MAIL_ADDR}\" \n" \
+             "-execd_spool_dir \"${CFG_EXE_SPOOL}\" \n"   
    $INFOTEXT -wait -auto $AUTO -n "\nHit <RETURN> to continue >> "
    #Load configuration, show only critical errors
    "$SGE_ROOT/util/upgrade_modules/load_cc.sh" "$UPGRADE_BACKUP_DIR" -log "C" -newijs "$newIJS" \
 -execd_spool_dir "$CFG_EXE_SPOOL" -gid_range "$CFG_GID_RANGE" -admin_mail "$CFG_MAIL_ADDR"
    
-   exit 0
-   #TODO: run inst_sge -finish_upgrade to 
-   # 1. install new RC /SMF scripts on all host
-   # 2. clear spool dirs
+   if [ "$POST_UPDATE" != true ]; then
+      $INFOTEXT -n "\nIf loading the configuration suceeded run these additional commads:\n" \
+      "REQUIRED:\n" \
+      "inst_sge -upd-execds\n" \
+      "   This will initialize all execd spool directories\n"
+      if [ "$WINDOWS_SUPPORT" = true ]; then
+          $INFOTEXT -n "inst_sge -upd-win\n" \
+          "   This will connect to all windows execution hosts install new windows helper service\n" \
+          "   WARNING: If the host already runs a helper service of a different version (e.g. from 6.1 cluster)\n" \
+          "                   it will be overwritten by the new version and hosts will only work in 6.2 cluster\n"
+      fi
+      $INFOTEXT -n "OPTIONAL:" \
+      "inst_sge -upd-rc\n" \
+      "   This will create new RC scripts/SMF services for the new cluster (qmaster,execd,bdb)\n" \
+      "   WARNING: will silently remove existing conflicting files\n" \
+      "   TIP: If you don't want to enable SMF on Solaris run  inst_sge -post-upd-rc -nosmf\n" \
+      "\n" \
+      "TIP: Use inst_sge -post-upd to do all previous actions\n"
+      exit 0
+   fi
+fi
+
+if [ "$POST_UPDATE" = true ]; then
+   ALL_RC=true     #Do all hosts
+   ADD_RC=false
+   REMOVE_RC=false
+   DEL_EXECD_SPOOL=true
+   #Delete (create) execd spool dirs
+   ManipulateOneDaemonType "" execd ""
+   DEL_EXECD_SPOOL=false
+   REMOVE_RC=true
+   #Remove all old RC scripts
+   ManipulateOneDaemonType "" qmaster "61"
+   ManipulateOneDaemonType "" execd "61"
+   ManipulateOneDaemonType "" bdb "61"
+   REMOVE_RC=false
+   ADD_RC=true
+   #Add new rc scripts for whole cluster
+   ManipulateOneDaemonType "" bdb ""
+   ManipulateOneDaemonType "" qmaster ""
+   ManipulateOneDaemonType "" execd ""
+   exit
+fi
+
+#Delete all execd_spool dirs / create non-existing ones
+if [ "$DEL_EXECD_SPOOL" = true ]; then
+   ManipulateOneDaemonType "" execd ""
+   if [ "$UPDATE_RC" != true -a "$UPDATE_WIN" != true ]; then
+      exit
+   fi
+fi
+
+#Remove old RC and install new
+if [ "$UPDATE_RC" = true ]; then
+   ManipulateOneDaemonType "" qmaster "61"
+   ManipulateOneDaemonType "" execd "61"
+   ManipulateOneDaemonType "" bdb "61"
+   if [ "$UPDATE_WIN" != true ]; then
+      exit
+   fi
+fi
+
+#Remove old RC and install new
+if [ "$UPDATE_WIN" = true ]; then
+   if [ -f "$SGE_ROOT/$SGE_CELL/win_hosts_to_update" ]; then
+      list=`cat $UPGRADE_BACKUP_DIR/win_hosts_to_update`
+   else
+      $INFOTEXT -log "No windows hosts in the backup. Cannot upgrade windows helper service."
+      exit 2
+   fi
+   ALL_RC=false
+   ManipulateOneDaemonType $list execd ""
+   $INFOTEXT -log "After you verify that your windows hosts work, you may delete  %s file." "$SGE_ROOT/$SGE_CELL/win_hosts_to_update"
+   exit
 fi
 
 if [ "$BERKELEY" = "install" ]; then
@@ -749,12 +890,12 @@ if [ "$EXECD" = "install" -a "$UPDATE" != "true" ]; then
       AddLocalConfiguration_With_Qconf
       AddSubmitHostsExecd
       AddSGEStartUpScript $euid execd
-      SetupWinSvc execinst #service install during execd installation -> param: execinst
+      SetupWinSvc execinst     #service install during execd installation -> param: execinst
       StartExecd
       AddQueue
       GiveHints
       CheckRunningDaemon sge_execd
-         
+      
       if [ $? = 0 ]; then
          $INFOTEXT "Execd on host %s is running!\n" $h
          $INFOTEXT -log "Execd on host %s is running!\n" $h
@@ -875,8 +1016,6 @@ if [ "$EXECD" = "uninstall" ]; then
    else
       . $SGE_ROOT/$SGE_CELL/common/settings.sh
    fi
-
-   SourceSmfSupport
    
    FetchHostname
    SetupWinSvc uninstall
@@ -901,7 +1040,6 @@ if [ $BERKELEY = "uninstall" ]; then
       ProcessSGERoot
       GetCell
       ADMINUSER=`$SGE_UTILBIN/filestat -owner . 2> /dev/null`
-      SourceSmfSupport
       #SMF will stop the service on its own in RemoveRCScript
       if [ "$SGE_ENABLE_SMF" != "true" ]; then
          ExecuteRPCServerScript stop
@@ -939,7 +1077,6 @@ if [ $QMASTER = "uninstall" ]; then
    fi
 
    . $SGE_ROOT/$SGE_CELL/common/settings.sh
-   SourceSmfSupport
    ServiceTagsSupport
    RemoveQmaster
    MoveLog
@@ -1194,10 +1331,11 @@ if [ "$COPY_CA" = "true" ]; then
       CSP="true"
    fi
    CopyCA copyonly
-   if [ "$?" != 1 ]; then
+   ret=$?
+   if [ $ret -eq 0 ]; then
       $INFOTEXT "Copying certificates is complete!"
    fi
-   exit 0
+   exit $ret
 fi
 
 if [ $BACKUP = "true" ]; then
@@ -1237,7 +1375,7 @@ if [ $MAKE_RC = "true" ]; then
                 "does not exist. Exit." \$SGE_ROOT/$SGE_CELL/common/bootstrap
       exit 1
    fi
-
+   
    if [ -f $SGE_ROOT/$SGE_CELL/common/settings.sh ]; then
       . $SGE_ROOT/$SGE_CELL/common/settings.sh
    else
@@ -1245,7 +1383,7 @@ if [ $MAKE_RC = "true" ]; then
                 "   %s\n\n" \
                 "which is required to set the environment variables does not exist. Exit." \
                 \$SGE_ROOT/$SGE_CELL/common/settings.sh
-       exit 1
+      exit 1
    fi
 
    if [ -f $SGE_ROOT/$SGE_CELL/common/sgemaster ]; then
@@ -1260,7 +1398,7 @@ if [ $MAKE_RC = "true" ]; then
 
    CreateSGEStartUpScripts 0 true master
    CreateSGEStartUpScripts 0 true execd
-
+   
    $INFOTEXT "\nYour new startup scripts are created. You will find them in the\n" \
              "directory:\n\n" \
              "   %s\n\n" \
@@ -1268,10 +1406,10 @@ if [ $MAKE_RC = "true" ]; then
              "   %s\n" \
              "   %s\n\n" \
              \$SGE_ROOT/$COMMONDIR sgemaster_$DATE sgeexecd_$DATE
-
+   
    $INFOTEXT "Please now copy the new startup scripts to the system wide rc\n" \
              "file location on all qmaster, shadowd and execution hosts."
-
+   
 fi
 
 exit 0
