ZG-2009-01-26-0: Bugfix:      gui-installer: Should warn a user that some of  the                               selected components were not really selected                  Bugster:     6786371                  Bugfix:      gui-installer: it's not possible to switch-off                               'service automatic startup' feature                  Bugster:     6793169                  Bugfix:      gui-installer: should check bdb server spool dir                               permissions on the remote host                  Bugster:     6786338                  Bugfix:      gui-installer: qmaster spool dir permission check                               done locally                  Bugster:     6786355                  Bugfix:      gui-installer: GUI installer should generete                               auto_inst file before starting with the installation                  Bugster:     6786384                  Enhacem.:    Improve debugging capabilities                  Enhacem.:    Check the FS type of BDB spool directory remotely                  Review:      LP

diff --git a/source/clients/gui-installer/templates/check_host b/source/clients/gui-installer/templates/check_host
--- a/source/clients/gui-installer/templates/check_host
+++ b/source/clients/gui-installer/templates/check_host
@@ -31,24 +31,27 @@
 ##########################################################################
 #___INFO__MARK_END__
 
+# arguements
 IS_BDB=$1
 IS_QMASTER=$2
 IS_SHADOW=$3
 IS_EXECD=$4
 
-SPOOLING_METHOD=${cfg.spooling.method}
-DB_SPOOLING_SERVER=${cfg.db.spooling.server}
+SPOOLING_METHOD="${cfg.spooling.method}"
+DB_SPOOLING_SERVER="${cfg.db.spooling.server}"
+
+# exit code for run fuctions
 EXIT_CODE=0
 
 # run the command as admin user
 RunAsAdmin()
 {
    #Check the admin user exists on this machine
-   ${cfg.sge.root}/utilbin/${host.arch}/adminrun ${cfg.admin.user} echo
+   "${cfg.sge.root}"/utilbin/"${host.arch}"/adminrun "${cfg.admin.user}" echo
    if [ $? -ne 0 ]; then
-      exit 41  # admin user not known on this host
+      exit 50  # admin user not known on this host
    fi
-   ${cfg.sge.root}/utilbin/${host.arch}/adminrun ${cfg.admin.user} $@
+   "${cfg.sge.root}"/utilbin/"${host.arch}"/adminrun "${cfg.admin.user}" $@
 }
 
 # run the command as executor then if it fails as admin user
@@ -67,28 +70,29 @@ RunAsBoth()
 if [ "$IS_BDB" = true ]; then
    # if BDB server spooling is enabled check write permission on BDB spool dir
    if [ "$SPOOLING_METHOD" = "berkeleydb" -a "$DB_SPOOLING_SERVER" != "none"  ]; then
-      RunAsBoth test -w ${cfg.db.spooling.dir}
+      IsDirWritable "${cfg.db.spooling.dir}"
       if [ $EXIT_CODE -ne 0 ]; then
          exit 10;
       fi
    fi
 fi
 
+# returns with the first existing parent directory in the hierarchy
 GetFirstExistingDir()
 {
   dir=$1
-  tmp_dir=$1
 
   if [ ! -d $dir ]; then
-     while [ ! -d $tmp_dir ]; do
-        chown_dir=$tmp_dir
-        tmp_dir2=`dirname $tmp_dir`
-        tmp_dir=$tmp_dir2
+     while [ ! -d $dir ]; do
+        tmp_dir=`dirname $dir`
+        dir=$tmp_dir
      done
   fi
-  echo $tmp_dir
+  echo $dir
 }
 
+# checks whether the executor or the admin user has write permission on
+# the given directory even if the directory does not exist.
 IsDirWritable()
 {
    dir=`GetFirstExistingDir $1`
@@ -100,35 +104,43 @@ if [ "$IS_QMASTER" = true ]; then
    # TODO check qmaster port usage
 
    # check write permission on qmaster spool dir
-   IsDirWritable ${cfg.qmaster.spool.dir}
+   IsDirWritable "${cfg.qmaster.spool.dir}"
    if [ $EXIT_CODE -ne 0 ]; then
       exit 20;
    fi
 
    # check write permission on global execd spool dir
-   IsDirWritable ${cfg.execd.spool.dir}
+   IsDirWritable "${cfg.execd.spool.dir}"
    if [ $EXIT_CODE -ne 0 ]; then
       exit 21;
    fi
 
    # if JMX is enabled check write permission on JMX keystore dir
-   USE_JMX=${add.sge.jmx}
+   USE_JMX="${add.sge.jmx}"
    if [ "$USE_JMX" = true ]; then
       # TODO check JMX port usage
-      IsDirWritable ${cfg.sge.jmx.ssl.keystore}
+      IsDirWritable "${cfg.sge.jmx.ssl.keystore}"
       if [ $EXIT_CODE -ne 0 ]; then
          exit 22;
       fi
    fi
 
-   # if local BDB spooling is enabled check write permission on BDB spool dir
-   # if exists ->  fail
+   # if local BDB spooling is enabled ...
    if [ "$SPOOLING_METHOD" = "berkeleydb" -a "$DB_SPOOLING_SERVER" = "none"  ]; then
+      # ...fail if exists
       if [ -d ${cfg.db.spooling.dir} ]; then
          exit 24;
       fi
 
-      IsDirWritable ${cfg.db.spooling.dir}
+      # ...fail if FSType equals 'nfs'
+      FIRST_EXISTING_DIR=`GetFirstExistingDir "${cfg.db.spooling.dir}"`
+      fstype=`"${cfg.sge.root}"/utilbin/"${host.arch}"/fstype $FIRST_EXISTING_DIR`
+      if [ "$fstype" = "nfs" ]; then
+         exit 25;
+      fi
+
+      # ...check write permission on BDB spool dir
+      IsDirWritable "${cfg.db.spooling.dir}"
       if [ $EXIT_CODE -ne 0 ]; then
          exit 23;
       fi
@@ -144,7 +156,7 @@ if [ "$IS_EXECD" = true ]; then
    # TODO check execd port usage
 
    # check write permission on local execd spool dir
-   IsDirWritable ${cfg.exec.spool.dir.local}
+   IsDirWritable "${cfg.exec.spool.dir.local}"
    if [ $EXIT_CODE -ne 0 ]; then
       exit 40;
    fi
