LP-2009-02-06-0: Bugfix:      inst_sge -copycerts in AUTO mode does not work                  Bugfix:      gui-installer: IPs treated as hostnames                  Bugfix:      gui-installer: prerequisites/final tasks now                               displayed in the install list                  Bugfix:      gui-installer: Can't add only admin/submit hosts                  Bugfix:      gui-installer: admin/submit only hosts should not                               skipped by the installer                  Bugfix:      gui-installer: Many errors not discovered when rsh                               is used (rsh always returns 0)                  Bugfix:      gui-installer: Removed unnecessary fields in CSP                               certificate screen                  Bugfix:      gui-installer: admin/submit host list in the final                               readme may be incomplete                  Bugfix:      gui-installer: CSP panel shown in incorrect                               scenarios                  Bugfix:      gui-installer: ProgressBar sometimes not shown                  Enhancem:    gui-installer: Improved task timeout times                  Enhancem.:   gui-installer: Improved installation log formatting                  Enhancem.:   gui-installer: check_host does not need to be done                               for admin/submit only hosts                  Enhacemm.:   gui-installer: Improved installation panel UE                  Cleanup:     gui-installer: Util and CommandExecutor                  Review:      ZG

diff --git a/source/clients/gui-installer/templates/install_component b/source/clients/gui-installer/templates/install_component
--- a/source/clients/gui-installer/templates/install_component
+++ b/source/clients/gui-installer/templates/install_component
@@ -321,25 +321,32 @@ GenerateResultOutput()
 	LOG_FILE=`echo $2 | grep "Install log can be found in:" | awk '{print $NF}'`
 	EXIT_CODE=$3
 	
-	if [ -n "$EXIT_CODE" -a "$EXIT_CODE" -gt 0 ]; then
-		echo "___EXIT_CODE_${EXIT_CODE}___"
+	if [ -n "$EXIT_CODE" -a "$EXIT_CODE" -ne 0 ]; then
 		if [ -z "$2" ]; then
+           echo "___EXIT_CODE_${EXIT_CODE}___"
 		   exit $EXIT_CODE
 		fi
-   fi
+    fi
 	
-   if [ ! -f "$LOG_FILE" ]; then
-	  echo "Log file $LOG_FILE does not exit!"
-   else
-      echo "___LOG_START_${COMPONENT}___"
-      cat "$LOG_FILE"
-      echo "___LOG_END_${COMPONENT}___"
-		if [ "$EXIT_CODE" -ne 0 ]; then
-         exit $EXIT_CODE
-		fi
-	fi
+   cat "$LOG_FILE"
+   if [ "$EXIT_CODE" -ne 0 ]; then
+      echo "___EXIT_CODE_${EXIT_CODE}___"
+      exit $EXIT_CODE
+   fi
 }
 
+#Genaretes output consisting of the exit code and log file
+# $1 ... output to be in a log
+# $2 ... EXIT_CODE
+ExitAndLog()
+{
+   EXIT_CODE=$2
+   echo "$1"
+   if [ "$EXIT_CODE" -ne 0 ]; then
+         echo "___EXIT_CODE_${EXIT_CODE}___"
+   fi
+   exit $EXIT_CODE
+}
 
 NOEXIT_OK=0
 EXIT_PREVIOUS_COMPONENT_DETECTED=10
@@ -369,7 +376,7 @@ if [ "$IS_BDB" = true ]; then
          fi
       else
 	    #Conflicting installation detected
-        GenerateResultOutput "BDB" "" $EXIT_PREVIOUS_COMPONENT_DETECTED
+        ExitAndLog "BDB spooling directory $DB_SPOOLING_DIR already exists." $EXIT_PREVIOUS_COMPONENT_DETECTED
       fi
    fi
    RES=`${cfg.sge.root}/inst_sge -db -noremote -autogui`
@@ -394,17 +401,17 @@ if [ "$IS_QMASTER" = true ]; then
          fi
       else
          #Conflicting installation detected 
-         GenerateResultOutput "QMASTER" "" $EXIT_PREVIOUS_COMPONENT_DETECTED
+         ExitAndLog "${cfg.sge.root}/$CELL_NAME/common/bootstrap file already exits." $EXIT_PREVIOUS_COMPONENT_DETECTED
       fi
    fi
    RES=`${cfg.sge.root}/inst_sge -m $QMASTER_FLAGS -noremote -autogui`
    ret=$?
    #Generate a result based
    GenerateResultOutput "QMASTER" "$RES" $ret
-   qmaster_first_task=true
 fi
 
-if [ -n "${first_install_task}" -o "$qmaster_first_task" = true ]; then
+if [ -n "${first_install_task}" ]; then
+   echo "Prerequisities"
    #Add all hosts as admin hosts on qmaster host only if this is a first task or right after the installation
    #Only first installation tasks have $cfg.allhosts set (no action otherwise)
    ARCH=`sh -c ${cfg.sge.root}/util/arch 2>/dev/null`
@@ -417,10 +424,11 @@ if [ -n "${first_install_task}" -o "$qmaster_first_task" = true ]; then
    if [ -n "${gui_alladminhosts}" ]; then
       list="${gui_alladminhosts}"
       for host in $list ; do
+         echo "Adding \"$host\" as admin host ..."
          if [ "$QMASTER_HOST" != "$CURRENT_HOST" ]; then
-            $SHELL_NAME $QMASTER_HOST "sh -c '. ${cfg.sge.root}/${cfg.cell.name}/common/settings.sh ; qconf -ah '${host}" >/dev/null 2>&1
+            $SHELL_NAME $QMASTER_HOST "sh -c '. ${cfg.sge.root}/${cfg.cell.name}/common/settings.sh ; qconf -ah '${host}" 2>&1
          else
-            sh -c '. ${cfg.sge.root}/${cfg.cell.name}/common/settings.sh ; qconf -ah '${host} >/dev/null 2>&1
+            sh -c '. ${cfg.sge.root}/${cfg.cell.name}/common/settings.sh ; qconf -ah '${host} 2>&1
          fi
       done
    fi
@@ -435,22 +443,27 @@ if [ -n "${first_install_task}" -o "$qmaster_first_task" = true ]; then
       total=0
       failed=0
       for host in $list ; do
-         RES=`${cfg.sge.root}/inst_sge $CSP_FLAGS -copycerts $host`
+         RES=`${cfg.sge.root}/inst_sge -autogui $CSP_FLAGS -copycerts $host`
          ret=$?
          if [ "$ret" -ne 0 ]; then
             echo "Copying CSP certificates to host $host failed! Further component installation will not work due to missing certificates."
             failed=`expr $failed + 1`
          else
-            echo "Copying CSP certificates to host $host succeeded."
+            echo "Copied CSP certificates to host \"$host\""
          fi
          total=`expr $total + 1`
       done
       #Exit with failed dependancy only if all copy tasks fail
       #TODO: Task must be displayed in the dependancy list!
       if [ $total -eq $failed ]; then
-         GenerateResultOutput "COPY_CSP_CERTIFICATES" "Copying CSP certificates failed for all hosts! Further component installations would fail due to missing certificates. Try inst_sge -copycerts manually for each host" $EXIT_PREVIOUS_COMPONENT_DETECTED
+         ExitAndLog "Copying CSP certificates failed for all hosts! Further component installations will fail due to missing certificates. Try inst_sge -copycerts manually for each host" 1
+      elif [ $failed -gt 0 ]; then
+         ExitAndLog "Copying CSP certificates failed for ${failed}/${total} hosts! Further component installations will fail due to missing certificates on failed hosts. Try inst_sge -copycerts manually for each host where installation failed." 0
+      else
+         ExitAndLog "CSP certificates copied sucessfully to all hosts." 0
       fi
    fi
+   ExitAndLog "Prerequisities done." 0
 fi
 
 if [ "$IS_SHADOW" = true ]; then
@@ -471,7 +484,7 @@ if [ "$IS_SHADOW" = true ]; then
          fi
       elif [ -n "$RES" ]; then
          #Conflicting installation detected 
-         GenerateResultOutput "SHADOW" "" $EXIT_PREVIOUS_COMPONENT_DETECTED
+         ExitAndLog "${cfg.sge.root}/$CELL_NAME/common/shadow_masters already contains host \"$EXEC_HOST_LIST\"." $EXIT_PREVIOUS_COMPONENT_DETECTED
       fi
    fi
    RES=`${cfg.sge.root}/inst_sge -sm -noremote -autogui`
@@ -481,7 +494,7 @@ fi
 if [ "$IS_EXECD" = true ]; then
    ENFORCED_HOSTNAME="$EXEC_HOST_LIST"
    host="$EXEC_HOST_LIST"
-   if [ -n "$EXECD_SPOOL_DIR_LOCAL" -a -f "$EXECD_SPOOL_DIR_LOCAL" ]; then
+   if [ -n "$EXECD_SPOOL_DIR_LOCAL" -a -d "$EXECD_SPOOL_DIR_LOCAL" ]; then
       local_exists=true
    fi   
    #Execd is considered installed if EXECD_(LOCAL)SPOOL_DIR/$host exists"   
@@ -498,7 +511,11 @@ if [ "$IS_EXECD" = true ]; then
          fi
       else
          #Conflicting installation detected 
-         GenerateResultOutput "EXECD" "" $EXIT_PREVIOUS_COMPONENT_DETECTED
+         if [ "$local_exists" ]; then
+            ExitAndLog "Local execution spooling directory \"$EXECD_SPOOL_DIR_LOCAL\" already exists." $EXIT_PREVIOUS_COMPONENT_DETECTED
+         else
+            ExitAndLog "Execution spooling directory \"$EXECD_SPOOL_DIR/$host\" already exists." $EXIT_PREVIOUS_COMPONENT_DETECTED
+         fi
       fi
    fi
    RES=`${cfg.sge.root}/inst_sge -x -noremote -autogui`
@@ -525,17 +542,19 @@ if [ -n "${last_install_task}" ]; then
       fi
       sh -c '. ${cfg.sge.root}/${cfg.cell.name}/common/settings.sh ; qconf -dh '$host >/dev/null 2>&1
    done
+   echo "Setting submit hosts ..."
    #Add all submit hosts
    list="${gui_allsubmithosts}"
    for host in $list; do
-      sh -c '. ${cfg.sge.root}/${cfg.cell.name}/common/settings.sh ; qconf -as '$host >/dev/null 2>&1
+      sh -c '. ${cfg.sge.root}/${cfg.cell.name}/common/settings.sh ; qconf -as '$host 2>&1
    done
    #Same logic for admin hosts
    #Add all admin hosts
    SKIPPED_FOUND=false
+   echo "Setting admin hosts ..."
    list="${gui_alladminhosts}"
    for host in $list ; do
-      sh -c '. ${cfg.sge.root}/${cfg.cell.name}/common/settings.sh ; qconf -ah '$host >/dev/null 2>&1
+      sh -c '. ${cfg.sge.root}/${cfg.cell.name}/common/settings.sh ; qconf -ah '$host 2>&1
       if [ "$host" = "$SKIPPED_HOST" ]; then
          SKIPPED_FOUND=true
       fi
@@ -546,6 +565,7 @@ if [ -n "${last_install_task}" ]; then
    fi
    #TODO: could verify that new qconf -ss/sh output contains all new hosts
    #TODO: Additional final verification can go here
+   ExitAndLog "Admin and submit hosts set." 0
 fi
 
 if [ -z "$EXIT_CODE" ]; then
