JG-2007-04-19-0: Enhancem.: New architecture strings ulx-* and usol-* for older,                             no longer officially supported OS versions.                             Some cleanup of distinst and sge_arch.c.                  Review:    RD Issue number: Obtained from: Submitted by: Reviewed by:

diff --git a/source/dist/util/arch b/source/dist/util/arch
--- a/source/dist/util/arch
+++ b/source/dist/util/arch
@@ -171,60 +171,80 @@ HP-UX)
    esac
    ;;
 Linux)
+   unsupported=""
+
    case $osmachine in
    i*86)
-     lxmachine=x86
-     ;;
+      lxmachine=x86
+      ;;
    alpha)
-     lxmachine=alpha
-     ;;
+      lxmachine=alpha
+      ;;
    sparc)
-     lxmachine=sparc
-     ;;
+      lxmachine=sparc
+      ;;
    sparc64)
-     lxmachine=sparc
-     ;;
+      lxmachine=sparc
+      ;;
    x86_64)
-     lxmachine=amd64
-     ;;
+      lxmachine=amd64
+      ;;
    ia64)
-     lxmachine=ia64
-     ;;
+      lxmachine=ia64
+      ;;
    ppc*)
-     lxmachine=ppc
-     ;;
+      lxmachine=ppc
+      ;;
    *)
-     lxmachine=UNSUPPORTED-linux
+      unsupported="UNSUPPORTED-"
+      lxmachine=$osmachine
    esac
 
    case $osrelease in
    2.4.*)
+      lxrelease=24
+
+      # verify the GNU C lib version
       # For an alternative means to determine GNU C lib version see
       # http://www.gnu.org/software/libc/FAQ.html#s-4.9
       case $lxmachine in
       amd64)
-        strings /lib64/libc.so.6 | grep "GNU C Library" | grep "2\.0" 2>&1 > /dev/null
-        ;;
+         libc_string=`strings /lib64/libc.so.6 | grep "GNU C Library"`
+         ;;
       ia64)
-        strings /lib/libc.so.6.1 | grep "GNU C Library" | grep "2\.0" 2>&1 > /dev/null
-        ;;
+         libc_string=`strings /lib/libc.so.6.1 | grep "GNU C Library"`
+         ;;
       *)
-        strings /lib/libc.so.6 | grep "GNU C Library" | grep "2\.0" 2>&1 > /dev/null
+         libc_string=`strings /lib/libc.so.6 | grep "GNU C Library"`
+         ;;
       esac
 
-      if [ $? -eq 0 ]; then
-         lxrelease=UNSUPPORTED-linux2.2-glibc2.0
+      # retrieving libc version failed
+      if [ $? -ne 0 ]; then
+         unsupported="UNSUPPORTED-"
+         lxrelease="24-GLIBC"
       else
-         lxrelease=24
+         libc_version=`echo $libc_string | tr ' ' '\n' | grep "2\." | cut -f 2 -d "."`
+         case $libc_version in
+         2)
+            unsupported="u"
+            ;;
+         3|4|5)
+            ;;
+         *)
+            unsupported="UNSUPPORTED-"
+            lxrelease=24-GLIBC-2.${libc_version}
+         esac
       fi
       ;;
    2.6.*)
       lxrelease=26
       ;;
    *)
-      lxrelease=-UNSUPPORTED-$osrelease
+      unsupported="UNSUPPORTED-"
+      lxrelease=$osrelease
    esac
-   ARCH=lx${lxrelease}-${lxmachine}
+   ARCH=${unsupported}lx${lxrelease}-${lxmachine}
    ;;
 OSF1)
    case $osrelease in
@@ -247,28 +267,39 @@ SunOS)
    i86*)
       ARCH=sol-x86
       case $osrelease in
-      5.[7891]*)
+      5.[8]*)
+         ARCH=usol-x86
+         ;;
+      5.[91]*)
          if [ `isainfo -b` = 64 ]; then
             ARCH=sol-amd64
          else
             ARCH=sol-x86
          fi
+         ;;
+      *)
+         ARCH=UNSUPPORTED-SunOS-$osrelease
+         ;;
       esac
       ;;
    *)
       case $osrelease in
-      5.[7891]*)
+      5.[7]*)
+         if [ `isainfo -b` = 64 ]; then
+            ARCH=usol-sparc64
+         else
+            ARCH=usol-sparc
+         fi
+         ;;
+      5.[891]*)
          if [ `isainfo -b` = 64 ]; then
             ARCH=sol-sparc64
          else
             ARCH=sol-sparc
          fi
          ;;
-      5.6)
-         ARCH=sol-sparc
-         ;;
       *)
-         ARCH=UNSUPPORTED-sun4-$osrelease
+         ARCH=UNSUPPORTED-SunOS-$osrelease
          ;;
       esac
       ;;
