AS-2004-01-30-1 Change architecture names according to Issue #644

diff --git a/source/dist/util/arch b/source/dist/util/arch
--- a/source/dist/util/arch
+++ b/source/dist/util/arch
@@ -37,87 +37,100 @@
 #  The original idea of "aimk" where this script is based on came from the
 #  PVM 3.x distribution, 22 Jul 1991 Robert Manchek manchek@CS.UTK.EDU. 
 #
-#  call:   arch       (print SGE architecture string)
+#  call:   arch       (print SGEEE architecture string)
 #          arch -m    (print default MANPATH of system)
 #          arch -mt   (print either "man" or "catman")
 #          arch -lib  (print name of variable to extend shared library path)
-#
 
-# On some architectures, it is necessicary to run the manpath(1) command
+# On some architectures, it is necessary to run the manpath(1) command
 # with the user's path instead of our "safe" one.  Thus we need to
 # save the old value of PATH for later restoration.
+#
 SAFE_PATH=/bin:/usr/bin:/usr/sbin
 OLD_PATH=$PATH
 PATH=$SAFE_PATH
 
 ARCH=UNKNOWN
 
-if [ -x /usr/bin/uname ]; then
-   os="`/usr/bin/uname -s`"
-   ht="`/usr/bin/uname -m`"
-   osht="$os,$ht"
-   case $osht in
-   Darwin,*)
-      ARCH=darwin
-      ;;
-   FreeBSD,*)
-      ARCH=fbsd-$ht
-      ;;
-   esac
+if [ -x /bin/uname ]; then
+   UNAME=/bin/uname
+elif [ -x /usr/bin/uname ]; then
+   UNAME=/usr/bin/uname
+else
+   echo ERROR: \"uname\" command not found
+   exit 1
 fi
 
-if [ -x /bin/uname ]; then
-   os="`/bin/uname -s`"
-   ht="`/bin/uname -m`"
-   osht="$os,$ht"
-   case $osht in
-   SUPER-UX,SX-4*)
-      ARCH=necsx4
+ossysname="`$UNAME -s`"
+osmachine="`$UNAME -m`"
+osrelease="`$UNAME -r`"
+
+case $ossysname in
+AIX)
+   osversion=`$UNAME -v`
+   case $osversion in
+   3)
+      ARCH=UNSUPPORTED-rs6000
       ;;
-   SUPER-UX,SX-[56]*)
-      ARCH=sx
-      ;;
-   SunOS,sun4*)
-      ARCH=sun4
-      ;;
-   SunOS,i86*)
-      ARCH=solaris86
-      ;;
-   AIX,*)
-      rev=`/bin/uname -v`
-      case $rev in
+   4)
+      case $osrelease in
+      1)
+         ARCH=UNSUPPORTED-aix41
+         ;;
+      2)
+         ARCH=UNSUPPORTED-aix42
+         ;;
       3)
-         ARCH=UNSUPPORTED-rs6000
+         ARCH=aix43
          ;;
-      4)
-         subrev=`/bin/uname -r`
-         case $subrev in
-         1)
-            ARCH=UNSUPPORTED-aix41
-            ;;
-         2)
-            ARCH=aix42
-            ;;
-         3)
-            ARCH=aix43
-            ;;
-         esac
-         ;;
-      5)
-         subrev=`/bin/uname -r`
-         case $subrev in
-         1)
-            ARCH=aix51
-            ;;
-         esac
       esac
       ;;
-   HP-UX,ia64)
-      ARCH=hp11-64
+   5)
+      case $osrelease in
+      1)
+         ARCH=aix51
+         ;;
+      *)
+         ARCH=UNSUPPORTED-aix-5-$osrelease
+         ;;
+      esac
       ;;
-   *,9000/*)
-      rev=`/bin/uname -r`
-      case $rev in
+   esac
+   ;;
+CRSOS)
+   if [ $osmachine = smp ]; then
+      ARCH=craysmp
+   fi
+   ;;
+Darwin)
+   ARCH=darwin
+   ;;
+FreeBSD)
+   ARCH=fbsd-$osmachine
+   ;;
+IRIX*)
+   case $osrelease in
+   4*)
+      ARCH=UNSUPPORTED-irix4
+      ;;
+   5*)
+      ARCH=UNSUPPORTED-irix5
+      ;;
+   6.5)
+      ARCH=irix65
+      ;;
+   6.*)
+      ARCH=UNSUPPORTED-irix-$osrelease
+      ;;
+   esac
+   ;;
+HP-UX)
+   case $osmachine in
+   ia64)
+      ARCH=hp11
+      ;;
+   9000/*)
+      case $osrelease in
       *.09.*)
          ARCH=UNSUPPORTED-hp
          ;;
@@ -128,78 +141,117 @@ if [ -x /bin/uname ]; then
          ARCH=hp10
          ;;
       *.11.*)
-         bits=`/usr/bin/getconf KERNEL_BITS`
+      if [ -x /usr/bin/getconf ]; then
+         bits="`/usr/bin/getconf KERNEL_BITS`"
          if [ $bits -eq 64 ]; then
-            ARCH=hp11-64
+            ARCH=hp11
          else
             ARCH=hp11
          fi
-         ;;
+      else
+         ARCH=hp11
+       fi
+      ;;
       esac
-      ;;
-   Linux,alpha)
-      ARCH=alinux
-      ;;
-   Linux,sparc)
-      ARCH=slinux
-      ;;
-   Linux,*)
-      rev="`/bin/uname -r`"
-      case $rev in
-      2.[24].*)
-         strings /lib/libc.so.6 | grep "GNU C Library" | grep 2/.0 2>&1 > /dev/null
-         if [ $? = 0 ]; then
-            ARCH=UNSUPPORTED-glinux20
-         else
-            ARCH=glinux
-         fi
-         ;;
-      *)
-         ARCH=UNSUPPORTED-linux
-         ;;
-      esac
-      ;;
-   *,alpha)
-      rev=`/usr/bin/uname -r`
-      case $rev in
-      V4*)
-         ARCH=osf4
-         ;;
-      V5*|T5*)
-         ARCH=tru64
-         ;;
-      *)
-         ARCH=UNSUPPORTED-osf
-         ;;
-      esac
-      ;;
-   CRSOS,smp)
-      ARCH=craysmp
-      ;;
+   esac
+   ;;
+Linux)
+   case $osmachine in
+   i*86)
+     lxmachine=x86
+     ;;
+   alpha)
+     lxmachine=alpha
+     ;;
+   sparc)
+     lxmachine=sparc
+     ;;
+   x86_64)
+     lxmachine=amd64
+     ;;
+   ia64)
+     lxmachine=ia64
+     ;;
+   *)
+     lxmachine=UNSUPPORTED-linux
    esac
 
-   if [ $ARCH = UNKNOWN ]; then
-      os="`/bin/uname -s`"
-      rel="`/bin/uname -r`"
-      osrel="$os,$rel"
-
-      case $osrel in
-      IRIX,4*)
-         ARCH=UNSUPPORTED-irix4
+   case $osrelease in
+   2.2.*)
+      lxrelease=22
+      ;;
+   2.4.*)
+      strings /lib/libc.so.6 | grep "GNU C Library" | grep "2\.0" 2>&1 > /dev/null
+      if [ $? = 0 ]; then
+         lxrelease=UNSUPPORTED-linux2.2-glibc2.0
+      else
+         lxrelease=24
+      fi
+      ;;
+   2.6.*)
+      lxrelease=26
+      ;;
+   *)
+      lxrelease=-UNSUPPORTED-$osrelease
+   esac
+   ARCH=lx${lxrelease}-${lxmachine}
+   ;;
+OSF1)
+   case $osrelease in
+   V4*)
+      ARCH=osf4
+      ;;
+    V5*|T5*)
+       ARCH=tru64
+       ;;
+    *)
+       ARCH=UNSUPPORTED-osf1-$osrelease
+       ;;
+    esac
+    ;;
+SunOS)
+   case $osmachine in
+   sun4)
+      ARCH=UNSUPPORTED-sun4
+      ;;
+   i86*)
+      ARCH=sol-x86
+      ;;
+   *)
+      case $osrelease in
+      5.[7891]*)
+         if [ `isainfo -b` = 64 ]; then
+            ARCH=sol-sparc64
+         else
+            ARCH=sol-sparc
+         fi
          ;;
-      IRIX,5*)
-         ARCH=UNSUPPORTED-irix5
+      5.6)
+         ARCH=sol-sparc
          ;;
-      IRIX*,6*)
-         ARCH=irix6
+      *)
+         ARCH=UNSUPPORTED-sun4-$osrelease
          ;;
       esac
-   fi
-fi
-
-if [ $ARCH = UNKNOWN ]; then
+      ;;
+   esac
+   ;;
+SUPER-UX)
+   case $osmachine in
+   SX-4*)
+      ARCH=UNSUPPORTED-necsx4
+      ;;
+   SX-[56]*)
+      ARCH=sx
+      ;;
+   *)
+      ARCH=UNSUPPORTED-SUPER-UX-$osmachine
+      ;;
+   esac
+   ;;
+*)
    if [ -f /unicos ]; then
-      if [ "`/bin/uname -m`" = "CRAY TS" ]; then
+      if [ "`$UNAME -m`" = "CRAY TS" ]; then
          if [ `/bin/target|/bin/grep ieee` = noieee ]; then
             ARCH=crayts
          else
@@ -208,65 +260,50 @@ if [ $ARCH = UNKNOWN ]; then
       else
          ARCH=cray
       fi
+   else
+      ARCH=UNSUPPORTED-${ossysname}-${osmachine}-${osrelease}
    fi
-fi
-
-if [ "$ARCH" = sun4 ]; then
-   REL=`/bin/uname -r`
-   case $REL in
-   5.[789]*)
-      if [ `isainfo -b` = 64 ]; then
-         ARCH=solaris64
-      else
-         ARCH=solaris
-      fi
-      ;;
-   5.[56]*)
-      ARCH=solaris
-      ;;
-   *)
-      ARCH=UNSUPPORTED-sun4-$REL
-      ;;
-   esac
-fi
+   ;;
+esac
 
 if [ "$1" = "-m" -o "$1" = "-mt" -o "$1" = "-lib" ]; then
    MANTYPE=man
    SHARED_LIBRARY_PATH="LD_LIBRARY_PATH"
+   DEFAULTMANPATH=/usr/man
    case $ARCH in
-   solaris|solaris64)
-      DEFAULTMANPATH=/usr/share/man
-      ;;
-   alinux|glinux)
-      if [ "`which manpath 2>/dev/null`" != "" ]; then
-         DEFAULTMANPATH=`manpath 2>/dev/null`
-      else
-         DEFAULTMANPATH=/usr/local/man:/usr/share/man:/usr/man:/usr/X11R6/man
-      fi
-      ;;
-   osf4|tru64)
-      DEFAULTMANPATH=/usr/share/man:/usr/dt/share/man:/usr/local/man
-      ;;
-   irix6|irix65)
-      DEFAULTMANPATH=/usr/share/catman:/usr/share/man:/usr/catman:/usr/man
-      MANTYPE=catman
-      ;;
-   hp10|hp11|hp11-64)
-      DEFAULTMANPATH=/usr/man:/usr/contrib/man:/usr/local/man
-      SHARED_LIBRARY_PATH="SHLIB_PATH"
-      ;;
-   aix42|aix43|aix51)
+   aix*)
       DEFAULTMANPATH=/usr/man
       SHARED_LIBRARY_PATH="LIBPATH"
+      ;;
+   darwin)
+      DEFAULTMANPATH=`/usr/bin/manpath -q`
+      SHARED_LIBRARY_PATH="DYLD_LIBRARY_PATH"
       ;;
    fbsd-*)
       PATH=$OLD_PATH
       DEFAULTMANPATH=`/usr/bin/manpath -q`
       PATH=$SAFE_PATH
       ;;
-   darwin)
-      DEFAULTMANPATH=`/usr/bin/manpath -q`
-      SHARED_LIBRARY_PATH="DYLD_LIBRARY_PATH"
+   hp*)
+      DEFAULTMANPATH=/usr/man:/usr/contrib/man:/usr/local/man
+      SHARED_LIBRARY_PATH="SHLIB_PATH"
+      ;;
+   irix65)
+      DEFAULTMANPATH=/usr/share/catman:/usr/share/man:/usr/catman:/usr/man
+      MANTYPE=catman
+      ;;
+   lx*)
+      if [ "`which manpath 2>/dev/null`" != "" ]; then
+         DEFAULTMANPATH=`manpath 2>/dev/null`
+      else
+         DEFAULTMANPATH=/usr/local/man:/usr/share/man:/usr/man:/usr/X11R6/man
+      fi
+      ;;
+   sol-*)
+      DEFAULTMANPATH=/usr/share/man
+      ;;
+   tru64)
+      DEFAULTMANPATH=/usr/share/man:/usr/dt/share/man:/usr/local/man
       ;;
    esac
 
