AS-2002-01-22-0 Added CA framework support

diff --git a/source/dist/util/arch_variables b/source/dist/util/arch_variables
--- a/source/dist/util/arch_variables
+++ b/source/dist/util/arch_variables
@@ -151,3 +151,265 @@ case $ARCH in
    exit 1
    ;;
 esac
+
+TOUCH=touch
+RM=rm
+MKDIR=mkdir
+CHMOD=chmod
+CHOWN=chown
+CP=cp
+
+# Some of the following shell function require thisvariables set to false or true
+#
+autoinst=false
+
+#--------------------------------------------------------------------------
+# Translate
+# create localized version of arguments using "gettext" and "printf"
+#
+# USES: variable "$translation" to either translate or not
+# 
+# $1 = 0  stdout, newline
+# $1 = 1  stderr, newline
+# $1 = 2  stdout, no newline
+# $1 = 3  stderr, no newline
+# $1 = 4  just store string in variable $transout
+# $2 = string to localize
+# $2- args not to localize
+#
+Translate()
+{
+   newline=""
+   stderr=0
+
+   if [ "$1" = 0 -o "$1" = 1 ]; then
+      newline="\n"
+   fi
+
+   if [ "$1" = 1 -o "$1" = 3 ]; then
+      stderr=1
+   fi
+   if [ "$1" = 4 ]; then
+      stderr=4
+   fi
+   shift
+
+   if [ "$translation" = 1 ]; then
+      transout=`env TEXTDOMAIN=$TEXTDOMAIN TEXTDOMAINDIR=$TEXTDOMAINDIR $GETTEXT "$1"`
+      shift
+      if [ $stderr = 4 ]; then
+         transout=`printf "$transout"$newline "$@"`
+      elif [ $stderr = 0 ]; then
+         printf "$transout"$newline "$@"
+      else
+         printf "$transout"$newline "$@" >&2
+      fi
+   else
+      transout="$1"
+      shift
+      if [ $stderr = 4 ]; then
+         transout=`printf "$transout" "$@"`
+      elif [ $stderr = 0 ]; then
+         printf "$transout"$newline "$@"    
+      else
+        printf "$transout"$newline "$@" >&2    
+      fi
+   fi
+}
+
+#-------------------------------------------------------------------------
+# WaitClear
+# Let user press the return key and print message
+#
+# USES: variables "$autoinst"
+#                 "$CLEAR"
+# $1 = clear  clear screen 
+# $1 =
+# $2 = no string - print default messages
+# $4 = arg       - print argument
+#
+WaitClear()
+{
+   do_clear=$1
+   text="$2"
+
+   if [ "$text" != "" ]; then
+      $ECHO "$text"
+   else
+      Translate 2 "Hit <RETURN> to continue >> "
+   fi
+
+   if [ $autoinst = true ]; then
+      echo
+   else
+      read INP_WaitClear
+
+      if [ $do_clear = clear ]; then
+         $CLEAR
+      fi
+   fi
+}
+
+#-------------------------------------------------------------------------
+# Enter: input is read and returned to stdout. If input is empty echo $1
+#
+# USES: variable "$autoinst" 
+#
+Enter()
+{
+   if [ $autoinst = true ]; then
+      $ECHO $1
+   else
+      read INP
+      if [ "$INP" = "" ]; then
+         $ECHO $1
+      else
+         $ECHO $INP
+      fi
+   fi
+}
+
+#-------------------------------------------------------------------------
+# YesNo: print argument and get YES/NO answer
+# $1 = string to print
+# $2 = default value if user enters return. Values are y,n,x (for no default)
+#
+YesNo()
+{
+   text=$1
+   default=$2
+   if [ "$default" = "" ]; then
+      default=x
+      text="$text >> \c"
+   else
+      Translate 4 "(y/n)"
+      text="$text $transout [$default] >> \c"
+   fi
+
+   if [ $autoinst = true -a $default != x -a $default != X ]; then
+      $ECHO "$text"
+      $ECHO $default
+      if [ $default = y -o $default = Y ]; then
+         return 0
+      else
+         return 1
+      fi
+   fi
+
+   YesNo_done=false
+   while [ $YesNo_done = false ]; do
+      $ECHO "$text"
+      read YesNo_INP
+
+      if [ "$YesNo_INP" = "" ]; then
+         if [ "$default" = y -o "$default" = Y ]; then
+            YesNo_INP=y
+         elif [ "$default" = n -o "$default" = N ]; then
+            YesNo_INP=n
+         fi
+      fi
+
+      case "$YesNo_INP" in
+         y|y|j|J)
+            YesNo_done=true
+            ret=0
+            ;;
+         n|N)
+            YesNo_done=true
+            ret=1
+            ;;
+      esac
+   done
+   return $ret
+}
+
+#-------------------------------------------------------------------------
+# Fatal Error: print message and exit
+#
+FatalError()
+{
+   $ECHO $*                           >&2
+   $ECHO ""                           >&2
+   Translate 1 "Installation failed. Exit."
+   $ECHO ""                           >&2
+   exit 1
+}
+
+#-------------------------------------------------------------------------
+# Execute command and exit if exit status != 0
+#
+Execute()
+{
+   if [ "$verbose" = true ]; then
+      $ECHO $*
+   fi
+   $*
+   if [ $? != 0 ]; then
+      $ECHO >&2
+      Translate 1 "Command failed: %s" "$*"
+      $ECHO "" >&2
+      Translate 1 "Probably a permission problem. Please check file access permissions."
+      Translate 1 "Check root read/write permission. Check if daemons are running."
+      $ECHO "" >&2
+      exit 1
+   fi
+}
+
+#-------------------------------------------------------------------------
+# Execute command as user $ADMINUSER and exit if exit status != 0
+# if ADMINUSER = default then execute command unchanged
+#
+# uses binary "adminrun" form SGE distribution
+#
+# USES: variables "$verbose"    (if set to "true" print arguments)
+#                  $ADMINUSER   (if set to "default" do not use "adminrun)
+#                 "$V5UTILBIN"  (path to the binary in utilbin)
+#
+ExecuteAsAdmin()
+{
+   if [ "$verbose" = true ]; then
+      $ECHO $*
+   fi
+
+   if [ $ADMINUSER = default ]; then
+      $*
+   else
+      $V5UTILBIN/adminrun $ADMINUSER $*
+   fi
+
+   if [ $? != 0 ]; then
+      $ECHO >&2
+      Translate 1 "Command failed: %s" "$*"
+      $ECHO "" >&2
+      Translate 1 "Probably a permission problem. Please check file access permissions."
+      Translate 1 "Check read/write permission. Check if daemons are running."
+      $ECHO "" >&2
+      exit 1
+   fi
+   return 0
+}
+
+#-------------------------------------------------------------------------
+# CreateAndMakeWriteable
+# create $1 as file and make it writable for everybody
+# uses variable $ADMINUSER
+#
+CreateAndMakeWriteable()
+{
+   ExecuteAsAdmin $TOUCH $1
+   if [ $ADMINUSER != default ]; then
+      ExecuteAsAdmin $CHMOD 666 $1
+   fi
+}
+
+#-------------------------------------------------------------------------
+# TruncCreateAndMakeWriteable
+# delete $1 as file and make it writable for everybody
+#
+TruncCreateAndMakeWriteable()
+{
+   if [ -f $1 ]; then
+      ExecuteAsAdmin $RM $1 
+   fi
+   CreateAndMakeWriteable $1
+}
