build env changes for uge extensions
suspend changes to qrsh client

added os-stub code for qrsh suspend feature

qrsh suspend changes for shepherd

double include of a header file

changed build procedure for solaris

diff --git a/source/aimk b/source/aimk
--- a/source/aimk
+++ b/source/aimk
@@ -177,6 +177,7 @@ usage:
    echo "-mo               -> generate the message catalogues (Solaris only)"
    echo "-no-core          -> don't compile the core system"
    echo "-no-dump          -> build binaries without libcore.so (Linux only)"
+   echo "-uge-ext          -> build binaries with Univa Extensions"
    echo "-no-java          -> don't compile Java[TM] class files"
    echo "-no-gui-inst      -> don't compile Java[TM] GUI installer"
    echo "-no-jni           -> don't compile JNI library"
@@ -234,6 +235,7 @@ set MSDIR            = ""
 set MAKEFILE         = "${SDIR}/common/Makefile.global"
 set SOLARIS_ONLY_64  = 0
 set ONLY_PARAM_SPEC  = 0
+set LIBS_DIR         = ".."
 
 # SGE_INPUT_CFLAGS will be taken from environment and added to CFLAGS
 if ( $?SGE_INPUT_CFLAGS ) then
@@ -307,6 +309,7 @@ set TPLIB            = ""  # 3rdparty libs
 set SLIBS            = ""
 set FLAGS_OUT        = "false"
 set DUMP             = 1
+set UGE_EXT          = 0   # Univa Extensions
 
 
 # Default settings for shared library creation
@@ -612,6 +615,9 @@ while ($#argv >= 1 && $?found)
       breaksw
    case "-no-dump":
       set DUMP = 0
+      breaksw
+   case "-uge-ext":
+      set UGE_EXT = 1
       breaksw
    case  "-no-java"
       set JAVA = 0
@@ -1995,6 +2001,21 @@ set ARCH_STRING  = SGE_ARCH_STRING='\"'${buildarch}'\"'
 set CFLAGS       = "-D$ARCH_STRING $CFLAGS"
 set DEPEND_FLAGS = "-D$ARCH_STRING $DEPEND_FLAGS"
 
+if ( $UGE_EXT == 1 ) then
+  if ( -d $UGE_LIBS ) then
+     set LFLAGS   = "$LFLAGS -L$UGE_EXT/$BUILDARCH/libs"
+     set LIBS_DIR = $UGE_EXT
+  else
+     echo "error: couldn't find  $UGE_LIBS"
+     echo "error: please"
+     echo "error: (a )update UGE_LIBS in aimk.site or aimk.private accordingly"
+     echo "error: (b) do not use aimk option -uge-ext"
+     exit 1
+  endif
+else
+  set LIBS_DIR = ${SDIR}
+endif
+
 if ( $JNI == 1 ) then
    set CORE_INCLUDE = "$CORE_INCLUDE -I${JAVA_HOME}/${JAVA_INCL}"
 
@@ -2576,6 +2597,7 @@ if ( "$CORE" == 1 && "$JAVA" != 2 ) then
          "CORELIB=$CORELIB" \
          "DEPEND_FLAGS=$DEPEND_FLAGS $CORE_INCLUDE" \
          "SDIR=$SDIR" "SOURCE=$SOURCE" "COMPILE_ARCH=$COMPILE_ARCH" \
+         "LIBS_DIR=$LIBS_DIR" \
          "SECLIB=$SECLIB" \
          "SECLIBS_STATIC=$SECLIBS_STATIC" \
          "WINGRIDLIB=$WINGRIDLIB" "WINGRIDLIB_DEP=$WINGRIDLIB_DEP" \
